const el=id=>document.getElementById(id),escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const number=value=>Number(value||0).toLocaleString('ko-KR'),ms=value=>value?`${number(value)}ms`:'—',date=value=>value?new Date(value).toLocaleString('ko-KR'):'—';
const statusLabel=value=>({completed:'완료',partial:'일부 완료',failed:'실패',processing:'처리 중',active:'정상',error:'오류',stale:'갱신 필요',paused:'일시정지',synced:'동기화',sync_failed:'동기화 실패',resumed:'재개',assigned:'담당자 지정',retry_requested:'재실행 요청',retry_completed:'재실행 완료'}[value]||value||'미확인');
const entityLabel=value=>({sales_order:'판매',inventory_snapshot:'재고',product_master:'상품 마스터',product_review:'리뷰·VOC'}[value]||value||'데이터');
const state={data:null,users:[],selectedJobId:null,busy:'',loading:false};

async function api(path,options={}){const response=await fetch(path,{credentials:'include',headers:options.body?{'content-type':'application/json'}:undefined,...options}),type=response.headers.get('content-type')||'';if(!type.includes('application/json'))throw new Error('운영 API에 연결할 수 없습니다.');const body=await response.json();if(!response.ok)throw new Error(response.status===401?'로그인이 필요합니다.':response.status===403?'관리자만 운영 상태를 관리할 수 있습니다.':body.error||`API ${response.status}`);return body}
function kpi(label,value,detail,risk=false){return `<article class="kpi ${risk?'risk':''}"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong><small>${escapeHtml(detail)}</small></article>`}
function toast(message,tone=''){let node=el('opsToast');if(!node){node=document.createElement('div');node.id='opsToast';node.className='ops-toast';document.body.append(node)}node.className=`ops-toast show ${tone}`;node.textContent=message;clearTimeout(node.timer);node.timer=setTimeout(()=>node.classList.remove('show'),3200)}
function userName(id){const user=state.users.find(item=>item.id===id);return user?.display_name||user?.email||'담당자 미지정'}
function latestSourceEvent(sourceId){return (state.data?.recoveryEvents||[]).find(event=>event.resource_id===sourceId)}

function sourceCard(source){
  const failed=source.status==='error'||source.data_mode==='stale',syncable=['sheet','sftp','api'].includes(source.source_type),event=latestSourceEvent(source.id),paused=source.status==='paused';
  const options=[`<option value="">담당자 선택</option>`,...state.users.filter(user=>user.status==='active').map(user=>`<option value="${escapeHtml(user.id)}" ${source.assigneeMembershipId===user.id?'selected':''}>${escapeHtml(user.display_name||user.email)}</option>`)].join('');
  return `<article class="source recovery-source ${failed?'error':''}"><div class="source-head"><div><strong>${escapeHtml(source.name||source.provider)}</strong><span>${escapeHtml(source.provider||'')}</span></div><em>${failed?'확인 필요':paused?'일시정지':'정상'}</em></div><p>${escapeHtml(source.last_sync_error||`마지막 정상 연결 ${date(source.last_successful_sync_at)}`)}</p><div class="source-owner"><label>담당자<select data-assignee-select="${source.id}">${options}</select></label><button class="mini-button" data-assign-source="${source.id}" ${state.busy===`assign:${source.id}`?'disabled':''}>${state.busy===`assign:${source.id}`?'저장 중':'지정'}</button></div><div class="source-actions">${syncable&&!paused?`<button class="mini-button primary" data-sync-source="${source.id}" ${state.busy===`sync:${source.id}`?'disabled':''}>${state.busy===`sync:${source.id}`?'재연결 중':'연결 재시도'}</button>`:source.source_type==='file'?'<a class="mini-button primary" href="./?page=connections">새 파일 등록</a>':''}<button class="mini-button" data-source-lifecycle="${source.id}" data-action="${paused?'resume':'pause'}" ${state.busy===`lifecycle:${source.id}`?'disabled':''}>${paused?'연결 재개':'일시정지'}</button></div><small class="source-history">담당 ${escapeHtml(userName(source.assigneeMembershipId))}${event?` · 최근 처리 ${escapeHtml(statusLabel(event.action.split('.').at(-1)))} ${date(event.created_at)}`:''}</small></article>`;
}

function importDetail(jobs){
  const job=jobs.find(item=>item.id===state.selectedJobId)||jobs[0];if(!job)return '<aside class="job-detail empty">조회 기간에 적재 작업이 없습니다.</aside>';
  const reason=job.summary?.failure?.message||job.errors?.[0]?.message||(job.status==='failed'?'처리 도중 중단되었습니다. 원본 파일로 재실행해 상세 원인을 확인하세요.':'오류 행을 수정한 뒤 다시 실행할 수 있습니다.'),retryable=['failed','partial'].includes(job.status)&&job.raw_upload_id;
  return `<aside class="job-detail"><header><div><small>${escapeHtml(entityLabel(job.entity_type))}</small><h3>${escapeHtml(job.filename||'파일명 없음')}</h3><p>${escapeHtml(String(job.id||'').slice(0,8))} · ${date(job.completed_at||job.created_at)}</p></div><span class="job-status ${job.status}">${escapeHtml(statusLabel(job.status))}</span></header><dl><div><dt>전체 행</dt><dd>${number(job.total_rows)}</dd></div><div><dt>정상 행</dt><dd>${number(job.success_rows)}</dd></div><div><dt>오류 행</dt><dd>${number(job.error_rows)}</dd></div><div><dt>신규 / 갱신</dt><dd>${number(job.inserted_rows)} / ${number(job.updated_rows)}</dd></div></dl><section class="failure-reason ${job.status==='failed'?'risk':''}"><small>확인할 내용</small><strong>${escapeHtml(reason)}</strong>${job.errors?.length?job.errors.slice(0,3).map(error=>`<p>${number(error.row_number)}행 · ${escapeHtml(error.field_name||'행')} · ${escapeHtml(error.message)}</p>`).join(''):''}</section><footer>${Number(job.error_rows)>0?`<button class="mini-button" data-download-errors="${job.id}">오류 CSV 다운로드</button>`:''}<a class="mini-button" href="./?page=connections">컬럼 매핑 확인</a>${retryable?`<button class="mini-button primary" data-retry-job="${job.id}" ${state.busy===`retry:${job.id}`?'disabled':''}>${state.busy===`retry:${job.id}`?'재실행 중':'원본으로 다시 실행'}</button>`:''}</footer></aside>`;
}

function render(data){
  state.data=data;const s=data.summary||{},attention=data.attention||[],sources=data.sources||[],imports=data.imports||[],endpoints=data.endpoints||[],analytics=data.analytics||[];
  if(!state.selectedJobId||!imports.some(job=>job.id===state.selectedJobId))state.selectedJobId=(imports.find(job=>job.status==='failed'||job.status==='partial')||imports[0])?.id||null;
  el('content').innerHTML=`<div class="ops-meta"><span class="health-state"><i></i>${attention.some(item=>item.severity==='critical')?'즉시 확인할 항목이 있습니다':'운영 상태 집계 완료'}</span><span>마지막 확인 ${date(data.generatedAt)}</span></div>
  <section class="kpis">${kpi('API p95',ms(s.apiP95Ms),`${number(s.apiRequests)}회 수집`,s.apiP95Ms>=2000)}${kpi('요청 오류',`${number(s.apiErrors)}건`,`느린 요청 ${number(s.slowApiRequests)}건`,s.apiErrors>0)}${kpi('AX 응답 p95',ms(s.axP95Ms),`${number(s.axRequests)}회 · 대체경로 ${number(s.axFallbacks)}회`,s.axP95Ms>=3000)}${kpi('데이터 소스',`${number(s.sourceTotal-s.sourceErrors)}/${number(s.sourceTotal)} 정상`,`${number(s.sourceErrors)}개 확인 필요`,s.sourceErrors>0)}${kpi('파일 적재',`${number(s.importTotal-s.importFailed)}건 처리`,`실패 ${number(s.importFailed)} · 일부 ${number(s.importPartial)}`,s.importFailed>0)}</section>
  <div class="grid"><section class="panel"><div class="panel-head"><div><h2>지금 확인할 운영 신호</h2><p>오류와 지연을 행동 우선순위로 변환했습니다.</p></div><span class="badge">${attention.length} SIGNALS</span></div><div class="attention-list">${attention.map(item=>`<article class="attention ${escapeHtml(item.severity)}"><i></i><div><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.detail)}</span></div></article>`).join('')}</div></section>
  <section class="panel"><div class="panel-head"><div><h2>데이터 연결 상태</h2><p>재연결·일시정지와 담당자 지정을 이 화면에서 처리합니다.</p></div><span class="badge">${sources.length} SOURCES</span></div><div class="source-grid recovery-grid">${sources.length?sources.map(sourceCard).join(''):'<div class="empty">등록된 데이터 소스가 없습니다.</div>'}</div></section></div>
  <section class="panel" style="margin-bottom:16px"><div class="panel-head"><div><h2>느린 API와 오류</h2><p>브라우저에서 익명 수집한 응답 시간이며 질문·파일 내용은 저장하지 않습니다.</p></div><span class="badge">p95 기준</span></div><div class="table-wrap"><table class="table"><thead><tr><th>API</th><th>요청</th><th>평균</th><th>p95</th><th>오류</th></tr></thead><tbody>${endpoints.length?endpoints.map(row=>`<tr><td><strong>${escapeHtml(row.name)}</strong></td><td>${number(row.requests)}</td><td>${ms(row.averageMs)}</td><td class="${row.p95Ms>=2000?'value-risk':''}">${ms(row.p95Ms)}</td><td class="${row.errors?'value-risk':''}">${number(row.errors)}건 · ${row.errorRate}%</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">아직 수집된 성능 기록이 없습니다. 서비스를 사용하면 자동으로 집계됩니다.</div></td></tr>'}</tbody></table></div></section>
  <section class="panel import-console"><div class="panel-head"><div><h2>파일 적재 문제 해결</h2><p>실패 작업을 선택해 원인과 오류 행을 확인하고 원본으로 다시 실행합니다.</p></div><span class="badge">${imports.length} JOBS</span></div><div class="import-workbench"><div class="table-wrap"><table class="table interactive-table"><thead><tr><th>파일</th><th>유형</th><th>상태</th><th>성공</th><th>오류</th><th>완료 시각</th></tr></thead><tbody>${imports.length?imports.map(job=>`<tr role="button" tabindex="0" data-job="${job.id}" class="${state.selectedJobId===job.id?'selected':''}"><td><strong>${escapeHtml(job.filename)}</strong><small>${escapeHtml(String(job.id||'').slice(0,8))}</small></td><td>${escapeHtml(entityLabel(job.entity_type))}</td><td class="${job.status==='failed'?'value-risk':''}">${escapeHtml(statusLabel(job.status))}</td><td>${number(job.success_rows)}</td><td class="${Number(job.error_rows)>0?'value-risk':''}">${number(job.error_rows)}</td><td>${date(job.completed_at||job.created_at)}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">조회 기간에 적재 작업이 없습니다.</div></td></tr>'}</tbody></table></div>${importDetail(imports)}</div></section>
  <section class="panel analytics-panel"><div class="panel-head"><div><h2>분석 파이프라인</h2><p>수요예측·할인 추천 자동 갱신</p></div><span class="badge">${analytics.length} RUNS</span></div><div class="table-wrap"><table class="table"><thead><tr><th>파이프라인</th><th>상태</th><th>완료 시각</th></tr></thead><tbody>${analytics.length?analytics.map(run=>`<tr><td><strong>${escapeHtml(run.pipeline)}</strong><small>${escapeHtml(run.error_message||'')}</small></td><td class="${run.status==='failed'?'value-risk':''}">${escapeHtml(statusLabel(run.status))}</td><td>${date(run.completed_at||run.started_at)}</td></tr>`).join(''):'<tr><td colspan="3"><div class="empty">조회 기간에 분석 실행 기록이 없습니다.</div></td></tr>'}</tbody></table></div><p class="foot-note">AX 답변 ${number(s.axMessages)}건 · 저장된 분석 캐시 재사용 ${number(s.cacheHits)}회 · 화면 전환 평균 ${ms(s.navigationAverageMs)}</p></section>
  <footer class="ops-footer">운영 지표에는 고객정보, 질문 원문, API 키 또는 업로드 파일 내용이 포함되지 않습니다.</footer>`;
  el('status').hidden=true;el('content').hidden=false;bindActions();
}

function bindActions(){
  document.querySelectorAll('[data-job]').forEach(row=>{const select=()=>{state.selectedJobId=row.dataset.job;render(state.data)};row.onclick=select;row.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();select()}}});
  document.querySelectorAll('[data-download-errors]').forEach(button=>button.onclick=()=>downloadErrors(button.dataset.downloadErrors));
  document.querySelectorAll('[data-retry-job]').forEach(button=>button.onclick=()=>retryJob(button.dataset.retryJob));
  document.querySelectorAll('[data-sync-source]').forEach(button=>button.onclick=()=>syncSource(button.dataset.syncSource));
  document.querySelectorAll('[data-source-lifecycle]').forEach(button=>button.onclick=()=>changeSource(button.dataset.sourceLifecycle,button.dataset.action));
  document.querySelectorAll('[data-assign-source]').forEach(button=>button.onclick=()=>assignSource(button.dataset.assignSource));
}

async function retryJob(jobId){if(!confirm('저장된 원본 파일과 확정 매핑으로 다시 실행할까요?'))return;state.busy=`retry:${jobId}`;render(state.data);try{const result=await api('/api/health?resource=operations',{method:'POST',body:JSON.stringify({action:'retry_import',jobId})});toast(`재실행 완료 · 정상 ${number(result.job?.successRows)}행`);await load(true)}catch(error){toast(`재실행 실패 · ${error.message}`,'error')}finally{state.busy='';render(state.data)}}
async function downloadErrors(jobId){try{const payload=await api(`/api/integrations/sources?resource=import-errors&jobId=${encodeURIComponent(jobId)}`),headers=['row_number','field_name','error_code','message','raw_row'],csvCell=value=>`"${String(typeof value==='object'?JSON.stringify(value):value??'').replace(/"/g,'""')}"`,rows=(payload.errors||[]).map(error=>headers.map(header=>csvCell(error[header])).join(',')),blob=new Blob([`\ufeff${headers.join(',')}\n${rows.join('\n')}`],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`${jobId.slice(0,8)}_errors.csv`;anchor.click();URL.revokeObjectURL(url);toast(`오류 ${number(payload.errors?.length)}건을 내려받았습니다.`)}catch(error){toast(`오류 다운로드 실패 · ${error.message}`,'error')}}
async function syncSource(sourceId){state.busy=`sync:${sourceId}`;render(state.data);try{const result=await api('/api/integrations/sync',{method:'POST',body:JSON.stringify({sourceId,action:'sync'})});toast(`재연결 완료 · ${number(result.import?.job?.successRows)}행 반영`);await load(true)}catch(error){toast(`재연결 실패 · ${error.message}`,'error')}finally{state.busy='';render(state.data)}}
async function changeSource(sourceId,action){state.busy=`lifecycle:${sourceId}`;render(state.data);try{await api('/api/integrations/sources',{method:'PATCH',body:JSON.stringify({sourceId,action})});toast(action==='resume'?'연결을 재개했습니다.':'연결을 일시정지했습니다.');await load(true)}catch(error){toast(`상태 변경 실패 · ${error.message}`,'error')}finally{state.busy='';render(state.data)}}
async function assignSource(sourceId){const select=document.querySelector(`[data-assignee-select="${sourceId}"]`),membershipId=select?.value;if(!membershipId){toast('담당자를 먼저 선택해주세요.','error');return}state.busy=`assign:${sourceId}`;render(state.data);try{await api('/api/health?resource=operations',{method:'POST',body:JSON.stringify({action:'assign_source',sourceId,membershipId})});toast('데이터 소스 담당자를 지정했습니다.');await load(true)}catch(error){toast(`담당자 지정 실패 · ${error.message}`,'error')}finally{state.busy='';render(state.data)}}

async function load(force=false){if(state.loading&&!force)return;state.loading=true;el('refresh').disabled=true;el('status').hidden=false;el('status').className='status loading';el('status').textContent='운영 상태를 불러오는 중입니다.';try{const [data,userPayload]=await Promise.all([api(`/api/health?resource=operations&days=${el('days').value}`),state.users.length?Promise.resolve({users:state.users}):api('/api/permissions/users').catch(()=>({users:[]}))]);state.users=userPayload.users||state.users;render(data)}catch(error){el('content').hidden=true;el('status').className='status error';el('status').innerHTML=`${escapeHtml(error.message)} <button type="button" id="retry">다시 시도</button>`;el('retry')?.addEventListener('click',()=>load(true))}finally{state.loading=false;el('refresh').disabled=false}}
el('refresh').addEventListener('click',()=>load(true));el('days').addEventListener('change',()=>load(true));load();setInterval(()=>{if(document.visibilityState==='visible')load(true)},60000);
