const el=id=>document.getElementById(id),escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const number=value=>Number(value||0).toLocaleString('ko-KR'),ms=value=>value?`${number(value)}ms`:'—',date=value=>value?new Date(value).toLocaleString('ko-KR'):'—';
const statusLabel=value=>({completed:'완료',partial:'일부 완료',failed:'실패',processing:'처리 중',active:'정상',error:'오류',stale:'갱신 필요'}[value]||value||'미확인');

async function api(path){const response=await fetch(path,{credentials:'include'}),type=response.headers.get('content-type')||'';if(!type.includes('application/json'))throw new Error('운영 API에 연결할 수 없습니다.');const body=await response.json();if(!response.ok)throw new Error(response.status===401?'로그인이 필요합니다.':response.status===403?'관리자만 운영 상태를 볼 수 있습니다.':body.error||`API ${response.status}`);return body}

function kpi(label,value,detail,risk=false){return `<article class="kpi ${risk?'risk':''}"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value)}</strong><small>${escapeHtml(detail)}</small></article>`}
function render(data){
  const s=data.summary||{},attention=data.attention||[],sources=data.sources||[],imports=data.imports||[],endpoints=data.endpoints||[],analytics=data.analytics||[];
  el('content').innerHTML=`<div class="ops-meta"><span class="health-state"><i></i>${attention.some(item=>item.severity==='critical')?'즉시 확인할 항목이 있습니다':'운영 상태 집계 완료'}</span><span>마지막 확인 ${date(data.generatedAt)}</span></div>
  <section class="kpis">${kpi('API p95',ms(s.apiP95Ms),`${number(s.apiRequests)}회 수집`,s.apiP95Ms>=2000)}${kpi('요청 오류',`${number(s.apiErrors)}건`,`느린 요청 ${number(s.slowApiRequests)}건`,s.apiErrors>0)}${kpi('AX 응답 p95',ms(s.axP95Ms),`${number(s.axRequests)}회 · 대체경로 ${number(s.axFallbacks)}회`,s.axP95Ms>=3000)}${kpi('데이터 소스',`${number(s.sourceTotal-s.sourceErrors)}/${number(s.sourceTotal)} 정상`,`${number(s.sourceErrors)}개 확인 필요`,s.sourceErrors>0)}${kpi('파일 적재',`${number(s.importTotal-s.importFailed)}건 처리`,`실패 ${number(s.importFailed)} · 일부 ${number(s.importPartial)}`,s.importFailed>0)}</section>
  <div class="grid"><section class="panel"><div class="panel-head"><div><h2>지금 확인할 운영 신호</h2><p>오류와 지연을 행동 우선순위로 변환했습니다.</p></div><span class="badge">${attention.length} SIGNALS</span></div><div class="attention-list">${attention.map(item=>`<article class="attention ${escapeHtml(item.severity)}"><i></i><div><strong>${escapeHtml(item.title)}</strong><span>${escapeHtml(item.detail)}</span></div></article>`).join('')}</div></section>
  <section class="panel"><div class="panel-head"><div><h2>데이터 연결 상태</h2><p>회사에 등록된 원천 데이터의 최신 상태</p></div><span class="badge">${sources.length} SOURCES</span></div><div class="source-grid">${sources.length?sources.map(source=>{const failed=source.status==='error'||source.data_mode==='stale';return `<article class="source ${failed?'error':''}"><strong>${escapeHtml(source.name||source.provider)}</strong><span>${escapeHtml(source.provider||'')}</span><em>${failed?'확인 필요':'정상'}</em><small>${escapeHtml(source.last_sync_error||date(source.last_successful_sync_at))}</small></article>`}).join(''):'<div class="empty">등록된 데이터 소스가 없습니다.</div>'}</div></section></div>
  <section class="panel" style="margin-bottom:16px"><div class="panel-head"><div><h2>느린 API와 오류</h2><p>브라우저에서 익명 수집한 응답 시간이며 질문·파일 내용은 저장하지 않습니다.</p></div><span class="badge">p95 기준</span></div><div class="table-wrap"><table class="table"><thead><tr><th>API</th><th>요청</th><th>평균</th><th>p95</th><th>오류</th></tr></thead><tbody>${endpoints.length?endpoints.map(row=>`<tr><td><strong>${escapeHtml(row.name)}</strong></td><td>${number(row.requests)}</td><td>${ms(row.averageMs)}</td><td class="${row.p95Ms>=2000?'value-risk':''}">${ms(row.p95Ms)}</td><td class="${row.errors?'value-risk':''}">${number(row.errors)}건 · ${row.errorRate}%</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">아직 수집된 성능 기록이 없습니다. 서비스를 사용하면 자동으로 집계됩니다.</div></td></tr>'}</tbody></table></div></section>
  <div class="grid"><section class="panel"><div class="panel-head"><div><h2>최근 파일 적재</h2><p>정상 행·오류 행과 처리 결과</p></div><span class="badge">${imports.length} JOBS</span></div><div class="table-wrap"><table class="table"><thead><tr><th>유형</th><th>상태</th><th>성공</th><th>오류</th><th>완료 시각</th></tr></thead><tbody>${imports.length?imports.map(job=>`<tr><td><strong>${escapeHtml(job.entity_type)}</strong><small>${escapeHtml(String(job.id||'').slice(0,8))}</small></td><td class="${job.status==='failed'?'value-risk':''}">${escapeHtml(statusLabel(job.status))}</td><td>${number(job.success_rows)}</td><td class="${Number(job.error_rows)>0?'value-risk':''}">${number(job.error_rows)}</td><td>${date(job.completed_at||job.created_at)}</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">조회 기간에 적재 작업이 없습니다.</div></td></tr>'}</tbody></table></div></section>
  <section class="panel"><div class="panel-head"><div><h2>분석 파이프라인</h2><p>수요예측·할인 추천 자동 갱신</p></div><span class="badge">${analytics.length} RUNS</span></div><div class="table-wrap"><table class="table"><thead><tr><th>파이프라인</th><th>상태</th><th>완료 시각</th></tr></thead><tbody>${analytics.length?analytics.map(run=>`<tr><td><strong>${escapeHtml(run.pipeline)}</strong><small>${escapeHtml(run.error_message||'')}</small></td><td class="${run.status==='failed'?'value-risk':''}">${escapeHtml(statusLabel(run.status))}</td><td>${date(run.completed_at||run.started_at)}</td></tr>`).join(''):'<tr><td colspan="3"><div class="empty">조회 기간에 분석 실행 기록이 없습니다.</div></td></tr>'}</tbody></table></div><p class="foot-note">AX 답변 ${number(s.axMessages)}건 · 저장된 분석 캐시 재사용 ${number(s.cacheHits)}회 · 화면 전환 평균 ${ms(s.navigationAverageMs)}</p></section></div>
  <footer class="ops-footer">운영 지표에는 고객정보, 질문 원문, API 키 또는 업로드 파일 내용이 포함되지 않습니다.</footer>`;
  el('status').hidden=true;el('content').hidden=false;
}

async function load(){el('refresh').disabled=true;el('status').hidden=false;el('status').className='status loading';el('status').textContent='운영 상태를 불러오는 중입니다.';try{render(await api(`/api/health?resource=operations&days=${el('days').value}`))}catch(error){el('content').hidden=true;el('status').className='status error';el('status').innerHTML=`${escapeHtml(error.message)} <button type="button" id="retry">다시 시도</button>`;el('retry')?.addEventListener('click',load)}finally{el('refresh').disabled=false}}
el('refresh').addEventListener('click',load);el('days').addEventListener('change',load);load();setInterval(()=>{if(document.visibilityState==='visible')load()},60000);
