const round=(value:number,digits=1)=>{const factor=10**digits;return Math.round(value*factor)/factor};
const money=(value:any)=>Number(value||0);

export function summarizeCustomerInsights(orders:any[]=[]){
  const paid=orders.filter(row=>String(row.status||'paid')!=='cancelled'),identified=paid.filter(row=>row.customer_token),byCustomer=new Map<string,any[]>();
  for(const order of identified){const key=String(order.customer_token),group=byCustomer.get(key)||[];group.push(order);byCustomer.set(key,group)}
  const repeatCustomers=new Set([...byCustomer].filter(([,rows])=>rows.length>=2).map(([key])=>key)),repeatOrders=identified.filter(row=>repeatCustomers.has(String(row.customer_token))).length,totalSales=paid.reduce((sum,row)=>sum+money(row.paid_amount),0);
  const cycles=[...byCustomer.values()].filter(rows=>rows.length>=2).map(rows=>{const dates=rows.map(row=>new Date(row.ordered_at).getTime()).filter(Number.isFinite).sort((a,b)=>a-b);return dates.length>=2?(dates.at(-1)!-dates[0])/(dates.length-1)/86400000:0}).filter(value=>value>0);
  const regionMap=new Map<string,any>();
  for(const order of paid){if(!order.shipping_region_1&&!order.shipping_region_2)continue;const label=[order.shipping_region_1,order.shipping_region_2].filter(Boolean).join(' '),group=regionMap.get(label)||{label,orders:0,net_sales:0,repeat_orders:0};group.orders++;group.net_sales+=money(order.paid_amount);if(order.customer_token&&repeatCustomers.has(String(order.customer_token)))group.repeat_orders++;regionMap.set(label,group)}
  const regions=[...regionMap.values()].map(row=>({...row,sales_share_pct:totalSales?round(row.net_sales/totalSales*100):0,average_order_value:row.orders?round(row.net_sales/row.orders,0):0,repeat_order_pct:row.orders?round(row.repeat_orders/row.orders*100):0})).sort((a,b)=>b.net_sales-a.net_sales);
  const segments={vip:0,loyal:0,growth:0,new:0};for(const rows of byCustomer.values()){if(rows.length>=6)segments.vip++;else if(rows.length>=4)segments.loyal++;else if(rows.length>=2)segments.growth++;else segments.new++}
  return {hasData:paid.length>0,summary:{anonymousCustomers:byCustomer.size,orders:paid.length,repeatCustomers:repeatCustomers.size,repeatCustomerPct:byCustomer.size?round(repeatCustomers.size/byCustomer.size*100):0,repeatOrderPct:identified.length?round(repeatOrders/identified.length*100):0,averagePurchaseCycleDays:cycles.length?round(cycles.reduce((a,b)=>a+b,0)/cycles.length):null,averageOrderValue:paid.length?round(totalSales/paid.length,0):0,totalSales},regions,segments,profileCoverage:{customerTokenPct:paid.length?round(identified.length/paid.length*100):0,shippingRegionPct:paid.length?round(paid.filter(row=>row.shipping_region_1||row.shipping_region_2).length/paid.length*100):0,demographicsAvailable:false}};
}

export function summarizeReturnInsights(orders:any[]=[],lines:any[]=[],products:any[]=[]){
  const orderMap=new Map(orders.map(row=>[String(row.id),row])),productMap=new Map(products.map(row=>[String(row.id),row])),channels=new Map<string,any>(),productGroups=new Map<string,any>();let orderedQty=0,returnedQty=0,cancelledQty=0,refundAmount=0,cancelAmount=0,processingCost=0;
  for(const line of lines){const order:any=orderMap.get(String(line.order_id));if(!order)continue;const qty=money(line.quantity),returned=Math.min(qty,money(line.returned_quantity)),cancelled=String(order.status||'paid')==='cancelled',lineSales=money(line.net_sales),estimatedList=money(line.unit_list_price)*qty;orderedQty+=qty;if(cancelled){cancelledQty+=qty;cancelAmount+=Math.max(lineSales,estimatedList)}else{returnedQty+=returned;refundAmount+=qty?lineSales*returned/qty:0}processingCost+=money(line.return_cost);
    const channel=String(order.channel_code||'미확인'),channelGroup=channels.get(channel)||{label:channel,ordered_qty:0,returned_qty:0,cancelled_qty:0,loss_amount:0};channelGroup.ordered_qty+=qty;channelGroup.returned_qty+=cancelled?0:returned;channelGroup.cancelled_qty+=cancelled?qty:0;channelGroup.loss_amount+=(cancelled?Math.max(lineSales,estimatedList):qty?lineSales*returned/qty:0)+money(line.return_cost);channels.set(channel,channelGroup);
    const product:any=productMap.get(String(line.product_id))||{},productKey=String(line.product_id||line.sku_id||'unknown'),productGroup=productGroups.get(productKey)||{label:product.product_name||product.product_code||'상품 미확인',product_code:product.product_code||null,image_url:product.image_url||null,ordered_qty:0,returned_qty:0,cancelled_qty:0};productGroup.ordered_qty+=qty;productGroup.returned_qty+=cancelled?0:returned;productGroup.cancelled_qty+=cancelled?qty:0;productGroups.set(productKey,productGroup)}
  const finish=(row:any)=>({...row,return_rate:row.ordered_qty?round(row.returned_qty/row.ordered_qty*100):0,cancel_rate:row.ordered_qty?round(row.cancelled_qty/row.ordered_qty*100):0});
  return {hasData:lines.length>0,summary:{orderedQty,returnedQty,cancelledQty,returnRate:orderedQty?round(returnedQty/orderedQty*100):0,cancelRate:orderedQty?round(cancelledQty/orderedQty*100):0,refundAmount:round(refundAmount,0),cancelAmount:round(cancelAmount,0),processingCost},channels:[...channels.values()].map(finish).sort((a,b)=>b.loss_amount-a.loss_amount),products:[...productGroups.values()].map(finish).sort((a,b)=>(b.return_rate+b.cancel_rate)-(a.return_rate+a.cancel_rate)),reasonCoverage:{available:false,message:'반품 사유 코드를 연결하면 사유별 손실 분석이 활성화됩니다.'}};
}
