import {forecastDemand} from './demand-forecast.js';
import {calculateInventoryPosition} from './inventory-position.js';
import {optimizeRebalancing} from './rebalancing-optimizer.js';
import {learningMultiplier} from './policy-learning.js';

const dayMs=86400000;
const dateKey=(value:Date|string|number)=>new Date(value).toISOString().slice(0,10);
const shiftDate=(value:string,days:number)=>dateKey(new Date(`${value}T00:00:00Z`).getTime()+days*dayMs);
const number=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0;

export function buildInternalInventoryPlan(input:any){
  const asOfDate=dateKey(input.asOfDate||new Date()),historyDays=Math.max(14,Number(input.historyDays||28)),horizonDays=Math.max(1,Number(input.horizonDays||7));
  const workspaceId=input.workspaceId||null,orders=input.orders||[],lines=input.lines||[],snapshots=input.snapshots||[],inboundOrders=input.inboundOrders||[],inboundLines=input.inboundLines||[],transfers=input.transfers||[],policies=input.policies||[],routes=input.routes||[],learningProfiles=input.learningProfiles||[];
  const orderMap=new Map(orders.map((row:any)=>[String(row.id),row])),historyStart=shiftDate(asOfDate,-historyDays);
  const salesByKeyDay=new Map<string,number>(),economics=new Map<string,{revenue:number,cost:number,qty:number}>();
  for(const line of lines){const order:any=orderMap.get(String(line.order_id));if(!order||!order.location_id||!line.sku_id)continue;const day=dateKey(order.ordered_at);if(day<historyStart||day>=asOfDate)continue;const key=`${line.sku_id}:${order.location_id}:${day}`,sold=Math.max(0,number(line.quantity)-number(line.returned_quantity));salesByKeyDay.set(key,(salesByKeyDay.get(key)||0)+sold);const item=economics.get(String(line.sku_id))||{revenue:0,cost:0,qty:0};item.revenue+=number(line.unit_sale_price)*sold;item.cost+=number(line.unit_cost)*sold;item.qty+=sold;economics.set(String(line.sku_id),item)}
  const latest=new Map<string,any>();for(const row of [...snapshots].sort((a,b)=>String(b.snapshot_at).localeCompare(String(a.snapshot_at)))){const key=`${row.sku_id}:${row.location_id}`;if(!latest.has(key))latest.set(key,row)}
  const inboundOrderMap=new Map(inboundOrders.map((row:any)=>[String(row.id),row])),inboundByKey=new Map<string,number>();for(const line of inboundLines){const order:any=inboundOrderMap.get(String(line.inbound_order_id));if(!order||!['confirmed','in_transit','partially_received'].includes(String(order.status)))continue;const remaining=Math.max(0,number(line.ordered_qty)-number(line.received_qty)-number(line.cancelled_qty));const key=`${line.sku_id}:${order.destination_location_id}`;inboundByKey.set(key,(inboundByKey.get(key)||0)+remaining)}
  const transferIn=new Map<string,number>(),transferOut=new Map<string,number>();for(const row of transfers){if(!['approved','in_transit'].includes(String(row.status)))continue;const amount=Math.max(0,number(row.approved_qty||row.recommended_qty));transferOut.set(`${row.sku_id}:${row.from_location_id}`,(transferOut.get(`${row.sku_id}:${row.from_location_id}`)||0)+amount);transferIn.set(`${row.sku_id}:${row.to_location_id}`,(transferIn.get(`${row.sku_id}:${row.to_location_id}`)||0)+amount)}
  const keys=new Set<string>([...latest.keys()]);for(const key of salesByKeyDay.keys())keys.add(key.split(':').slice(0,2).join(':'));
  const activePolicies=policies.filter((row:any)=>row.status==='active'&&String(row.effective_from||'')<=asOfDate&&(!row.effective_to||String(row.effective_to)>=asOfDate));
  const policyFor=(skuId:string,locationId:string)=>activePolicies.filter((row:any)=>(!row.sku_id||row.sku_id===skuId)&&(!row.location_id||row.location_id===locationId)).sort((a:any,b:any)=>(Number(b.sku_id!=null)+Number(b.location_id!=null))-(Number(a.sku_id!=null)+Number(a.location_id!=null))||number(a.priority)-number(b.priority))[0]||null;
  const positions:any[]=[],forecasts:any[]=[],optimizationPositions:any[]=[];
  for(const key of keys){const separator=key.indexOf(':'),skuId=key.slice(0,separator),locationId=key.slice(separator+1),snapshot=latest.get(key)||{},policy=policyFor(skuId,locationId),learned=learningMultiplier(learningProfiles,skuId,locationId),history=[];for(let offset=-historyDays;offset<0;offset++)history.push(salesByKeyDay.get(`${key}:${shiftDate(asOfDate,offset)}`)||0);const rawDaily=forecastDemand({history,horizonDays:1}),rawHorizon=forecastDemand({history,horizonDays,lostDemandUpliftRate:.08}),scale=(value:number)=>Math.max(0,value*learned.multiplier),dailyForecast={...rawDaily,p10Qty:scale(rawDaily.p10Qty),p50Qty:scale(rawDaily.p50Qty),p90Qty:scale(rawDaily.p90Qty),dailyMean:scale(rawDaily.dailyMean),lostDemandUpliftQty:scale(rawDaily.lostDemandUpliftQty)},horizonForecast={...rawHorizon,p10Qty:scale(rawHorizon.p10Qty),p50Qty:scale(rawHorizon.p50Qty),p90Qty:scale(rawHorizon.p90Qty),dailyMean:scale(rawHorizon.dailyMean),lostDemandUpliftQty:scale(rawHorizon.lostDemandUpliftQty)},position=calculateInventoryPosition({onHandQty:snapshot.on_hand_qty,reservedQty:snapshot.reserved_qty,availableQty:snapshot.available_qty,inboundConfirmedQty:inboundByKey.get(key),transferInQty:transferIn.get(key),transferOutQty:transferOut.get(key),damagedQty:snapshot.damaged_qty,safetyStockQty:snapshot.safety_stock_qty});
    positions.push({workspace_id:workspaceId,position_date:asOfDate,sku_id:skuId,location_id:locationId,on_hand_qty:position.onHandQty,reserved_qty:position.reservedQty,available_qty:position.availableQty,inbound_confirmed_qty:position.inboundConfirmedQty,transfer_in_qty:position.transferInQty,transfer_out_qty:position.transferOutQty,damaged_qty:position.damagedQty,safety_stock_qty:position.safetyStockQty,inventory_position_qty:position.inventoryPositionQty,stockout_flag:position.stockoutFlag,calculation_version:'internal-v1'});
    for(let day=1;day<=horizonDays;day++)forecasts.push({workspace_id:workspaceId,as_of_date:asOfDate,target_date:shiftDate(asOfDate,day),sku_id:skuId,location_id:locationId,p10_qty:dailyForecast.p10Qty,p50_qty:dailyForecast.p50Qty,p90_qty:dailyForecast.p90Qty,lost_demand_uplift_qty:dailyForecast.lostDemandUpliftQty,method:dailyForecast.method,model_version:'internal-v1',feature_version:'sales_inventory_v1',diagnostics:{history_days:historyDays,non_zero_days:history.filter(value=>value>0).length,learning_multiplier:learned.multiplier,learning_confidence:learned.confidence,learning_evidence_count:learned.evidenceCount,policy_candidate_id:learned.candidateId||null}});
    const margin=economics.get(skuId),unitMargin=margin?.qty?Math.max(0,(margin.revenue-margin.cost)/margin.qty):0;optimizationPositions.push({skuId,locationId,availableQty:position.availableQty,inventoryPositionQty:position.inventoryPositionQty,safetyStockQty:Math.max(position.safetyStockQty,horizonForecast.dailyMean*number(policy?.safety_stock_days)),forecastP90Qty:horizonForecast.p90Qty,dailyForecastQty:horizonForecast.dailyMean,minStockQty:number(policy?.min_stock_qty),maxStockQty:policy?.max_stock_qty,capacityQty:policy?.location_capacity_qty,packQty:number(policy?.order_pack_qty)||1,minTransferQty:number(policy?.min_transfer_qty)||1,maxTransferQty:policy?.max_transfer_qty,allowRebalancing:Boolean(policy?.allow_rebalancing),unitMargin})}
  const routeInputs=routes.filter((row:any)=>row.status==='active').map((row:any)=>({fromLocationId:row.from_location_id,toLocationId:row.to_location_id,active:true,minShipmentQty:number(row.min_shipment_qty),maxShipmentQty:row.max_shipment_qty,fixedCost:number(row.fixed_cost),variableCostPerUnit:number(row.variable_cost_per_unit),leadTimeDays:number(row.lead_time_days)}));
  const readyForRecommendations=activePolicies.length>0&&routeInputs.length>0;
  const recommendations=readyForRecommendations?optimizeRebalancing(optimizationPositions,{routes:routeInputs,budgetAmount:input.budgetAmount,minNetValue:number(input.minNetValue),limit:Number(input.limit||100)}):[];
  return {asOfDate,historyDays,horizonDays,positions,forecasts,recommendations,learning:{appliedProfiles:learningProfiles.length},readiness:{ready:readyForRecommendations,policyRows:activePolicies.length,routeRows:routeInputs.length,missing:[activePolicies.length?'':'inventory_policies',routeInputs.length?'':'logistics_routes'].filter(Boolean)}};
}
