import {measureInternalOutcome} from './outcome-measurement.js';
import {deriveForecastBiasCandidates} from './policy-learning.js';
import {insert,supabase,update} from './supabase.js';

async function rows(table:string,org:string,select:string,extra:Record<string,string>={}){const result:any[]=[],size=1000;for(let offset=0;;offset+=size){const query=new URLSearchParams({organization_id:`eq.${org}`,select,...extra}),page=(await supabase(`/rest/v1/${table}?${query}`,{serviceRole:true,headers:{Range:`${offset}-${offset+size-1}`,'Range-Unit':'items'}})).data||[];result.push(...page);if(page.length<size)break}return result}
const shift=(value:string,days:number)=>{const date=new Date(`${value}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)};

export async function refreshOrganizationOutcomes(organizationId:string,asOfDate:string){
  const outcomes=await rows('recommendation_outcomes',organizationId,'*',{outcome_status:'in.(pending,measuring)',measurement_end_date:`lte.${asOfDate}`});if(!outcomes.length)return {checked:0,completed:0,pending:0,insufficient:0};
  const lineIds=[...new Set(outcomes.map(row=>row.recommendation_line_id))],executionIds=[...new Set(outcomes.map(row=>row.execution_request_id).filter(Boolean))],earliest=outcomes.map(row=>shift(row.measurement_start_date,-28)).sort()[0];
  const [lines,executions,orders,salesLines]=await Promise.all([rows('recommendation_scenario_lines',organizationId,'*',{id:`in.(${lineIds.join(',')})`}),rows('execution_requests',organizationId,'*',{id:`in.(${executionIds.join(',')})`}),rows('sales_orders',organizationId,'id,location_id,ordered_at',{ordered_at:`gte.${earliest}T00:00:00Z`,order:'ordered_at.asc'}),rows('sales_order_lines',organizationId,'order_id,sku_id,quantity,returned_quantity,net_sales,unit_cost')]);
  const lineMap=new Map(lines.map(row=>[String(row.id),row])),executionMap=new Map(executions.map(row=>[String(row.id),row])),orderMap=new Map(orders.map(row=>[String(row.id),row])),orderDates=orders.map(row=>String(row.ordered_at)).sort(),dataStartDate=orderDates[0]?.slice(0,10)||'',watermark=orderDates.at(-1)?.slice(0,10)||'';let completed=0,pending=0,insufficient=0;
  for(const outcome of outcomes){const line:any=lineMap.get(String(outcome.recommendation_line_id)),execution:any=executionMap.get(String(outcome.execution_request_id));if(!line||!execution){await update('recommendation_outcomes',{id:`eq.${outcome.id}`,organization_id:`eq.${organizationId}`},{outcome_status:'insufficient_data',metrics:{reason:'missing_line_or_execution'},measured_at:new Date().toISOString()});insufficient++;continue}if(!outcome.learning_eligible||['unverified','inferred'].includes(String(outcome.verification_method))){pending++;continue}
    const sales=salesLines.flatMap(row=>{const order:any=orderMap.get(String(row.order_id));if(!order||String(order.location_id)!==String(line.to_location_id)||String(row.sku_id)!==String(line.sku_id))return [];const quantity=Math.max(0,Number(row.quantity||0)-Number(row.returned_quantity||0));return [{date:String(order.ordered_at).slice(0,10),quantity,netSales:Number(row.net_sales||0),unitCostAmount:Number(row.unit_cost||0)*quantity}]});const measured:any=measureInternalOutcome({measurementStartDate:outcome.measurement_start_date,measurementEndDate:outcome.measurement_end_date,dataWatermarkDate:watermark,dataStartDate,sales,executedQty:Number(outcome.executed_qty||execution.received_qty||execution.executed_qty||0),recommendedQty:Number(line.recommended_qty||0),expectedNetValue:Number(line.expected_net_value||0),expectedLogisticsCost:Number(line.expected_logistics_cost||0)});if(!measured.ready){if(measured.reason==='insufficient_baseline'){await update('recommendation_outcomes',{id:`eq.${outcome.id}`,organization_id:`eq.${organizationId}`},{outcome_status:'insufficient_data',metrics:measured,measured_at:new Date().toISOString()});insufficient++}else pending++;continue}await update('recommendation_outcomes',{id:`eq.${outcome.id}`,organization_id:`eq.${organizationId}`},{realized_sales_qty:measured.actualQty,avoided_stockout_qty:Math.max(0,measured.incrementalQty),realized_revenue_gain:measured.realizedRevenueGain,realized_margin_gain:measured.realizedMarginGain,realized_logistics_cost:measured.realizedLogisticsCost,realized_net_value:measured.realizedNetValue,forecast_error_pct:null,quantity_error_pct:measured.quantityErrorPct,outcome_status:'complete',metrics:{method:'directional_pre_execution_28d',...measured},measured_at:new Date().toISOString()});completed++}
  const [completedOutcomes,learningLines,existingCandidates]=await Promise.all([rows('recommendation_outcomes',organizationId,'*',{outcome_status:'eq.complete',learning_eligible:'eq.true'}),rows('recommendation_scenario_lines',organizationId,'id,sku_id,to_location_id'),rows('policy_change_candidates',organizationId,'*',{candidate_type:'eq.forecast_bias',status:'in.(proposed,approved,applied)'})]),derived=deriveForecastBiasCandidates(completedOutcomes,learningLines);let policyCandidates=0,guardrailStops=0;
  for(const candidate of derived){const matches=existingCandidates.filter(row=>String(row.sku_id)===candidate.skuId&&String(row.location_id)===candidate.locationId),applied=matches.find(row=>row.status==='applied'),existing=matches.find(row=>['proposed','approved'].includes(row.status)),values={workspace_id:null,sku_id:candidate.skuId,location_id:candidate.locationId,candidate_type:candidate.candidateType,current_value:candidate.currentValue,proposed_value:candidate.proposedValue,evidence_count:candidate.evidenceCount,evidence:candidate.evidence,expected_improvement:candidate.expectedImprovement,confidence:candidate.confidence,updated_at:new Date().toISOString()};if(applied){const negative=Number(candidate.expectedImprovement.positive_outcome_share)<.34&&candidate.evidenceCount>Number(applied.evidence_count||0);if(negative){await update('policy_change_candidates',{id:`eq.${applied.id}`,organization_id:`eq.${organizationId}`},{status:'expired',evidence:candidate.evidence,evidence_count:candidate.evidenceCount,expected_improvement:{...candidate.expectedImprovement,guardrail_reason:'positive_outcome_share_below_34pct'},updated_at:new Date().toISOString()});guardrailStops++}continue}if(existing)await update('policy_change_candidates',{id:`eq.${existing.id}`,organization_id:`eq.${organizationId}`},values);else await insert('policy_change_candidates',{organization_id:organizationId,...values});policyCandidates++}
  return {checked:outcomes.length,completed,pending,insufficient,policyCandidates,guardrailStops,dataWatermark:watermark};
}
