import {bodyJson,errorResponse,json} from '../http.js';
import {audit,insert,requestContext,requirePagePermission,supabase,update,workspaceId} from '../supabase.js';

const enc=encodeURIComponent;
const allowedDecisions=['approved','adjusted','rejected','held','cancelled'];
const statusByEvent:any={accepted:'accepted',dispatched:'in_progress',in_transit:'in_progress',partially_received:'partially_completed',received:'completed',cancelled:'cancelled',failed:'failed',manual_verified:null,file_reconciled:null,api_confirmed:null,inventory_inferred:null};
const verificationByEvent:any={manual_verified:['manual',.85],file_reconciled:['file_reconciled',.95],api_confirmed:['api_confirmed',1],inventory_inferred:['inferred',.65]};
async function list(table:string,context:any,select='*',extra:Record<string,string>={}){const query=new URLSearchParams({organization_id:`eq.${context.membership.organization_id}`,select,...extra}),ws=workspaceId(context);if(ws)query.set('workspace_id',`eq.${ws}`);return (await supabase(`/rest/v1/${table}?${query}`,{serviceRole:true})).data||[]}
async function recommendation(context:any,id:string){return (await list('recommendation_scenario_lines',context,'*',{id:`eq.${id}`,limit:'1'}))[0]||null}
const effectFor=(line:any,quantity:number)=>{const base=Math.max(0,Number(line.recommended_qty||0)),ratio=base?quantity/base:0;return {quantity,expected_margin_gain:Number(line.expected_margin_gain||0)*ratio,expected_logistics_cost:Number(line.expected_logistics_cost||0)*ratio,expected_net_value:Number(line.expected_net_value||0)*ratio,source_excess_after:Math.max(0,Number(line.source_excess_qty||0)-quantity),destination_shortage_after:Math.max(0,Number(line.destination_shortage_qty||0)-quantity)}};
async function workflow(context:any){
  const [scenarios,lines,decisions,executions,events,outcomes,skus,locations,candidates,forecasts]=await Promise.all([
    list('recommendation_scenarios',context,'id,scenario_key,scenario_type,as_of_date,horizon_days,status,engine_version,summary,generated_at',{order:'generated_at.desc',limit:'30'}),list('recommendation_scenario_lines',context,'*',{order:'created_at.desc',limit:'200'}),list('recommendation_decisions',context,'*',{order:'decided_at.desc',limit:'300'}),list('execution_requests',context,'*',{order:'requested_at.desc',limit:'200'}),list('execution_events',context,'*',{order:'occurred_at.desc',limit:'500'}),list('recommendation_outcomes',context,'*',{order:'measurement_end_date.desc',limit:'500'}),list('skus',context,'id,sku_code,product_id,size,color',{limit:'2000'}),list('locations',context,'id,location_code,location_name,location_type',{limit:'2000'}),list('policy_change_candidates',context,'*',{order:'created_at.desc',limit:'100'}),list('demand_forecasts',context,'sku_id,location_id,as_of_date,target_date,p50_qty,diagnostics',{order:'as_of_date.desc,target_date.asc',limit:'1000'})
  ]);return {scenarios,lines,decisions,executions,events,outcomes,skus,locations,policyCandidates:candidates,forecasts};
}
async function decide(context:any,body:any){
  requirePagePermission(context,'decisions','approve');const org=context.membership.organization_id,ws=workspaceId(context),line=await recommendation(context,String(body.recommendationLineId||''));if(!line)return json({ok:false,error:'Recommendation not found'},404);const decision=String(body.decision||'');if(!allowedDecisions.includes(decision))return json({ok:false,error:'Invalid decision'},400);if(['adjusted','rejected','held'].includes(decision)&&!String(body.reasonCode||'').trim())return json({ok:false,error:'변경·보류·거절 사유가 필요합니다.'},400);
  const quantity=['rejected','held','cancelled'].includes(decision)?0:Math.max(0,Number(body.quantity??line.recommended_qty));if(['approved','adjusted'].includes(decision)&&quantity<=0)return json({ok:false,error:'승인 수량은 0보다 커야 합니다.'},400);const fromId=body.fromLocationId??line.from_location_id,toId=body.toLocationId??line.to_location_id;if(['approved','adjusted'].includes(decision)&&line.action_type==='transfer'&&(!fromId||!toId||fromId===toId))return json({ok:false,error:'유효한 출발지와 도착지가 필요합니다.'},400);
  const current=(await list('recommendation_decisions',context,'id,decision_version',{recommendation_line_id:`eq.${line.id}`,is_current:'eq.true',order:'decision_version.desc',limit:'1'}))[0];if(current){const activeExecution=(await list('execution_requests',context,'id,status',{decision_id:`eq.${current.id}`,status:'not.in.(cancelled,failed)',limit:'1'}))[0];if(activeExecution)return json({ok:false,error:'이미 실행 요청이 생성된 결정은 취소 또는 실패 처리 후 변경할 수 있습니다.'},409);await update('recommendation_decisions',{id:`eq.${current.id}`,organization_id:`eq.${org}`},{is_current:false})}const expected=effectFor(line,quantity),record=(await insert('recommendation_decisions',{organization_id:org,workspace_id:ws,recommendation_line_id:line.id,decision,decision_version:Number(current?.decision_version||0)+1,decided_qty:quantity,decided_from_location_id:fromId||null,decided_to_location_id:toId||null,requested_execution_date:body.requestedExecutionDate||null,reason_code:body.reasonCode||null,note:body.note||null,actor_user_id:context.user.id,expected_effect_snapshot:expected,is_current:true,supersedes_decision_id:current?.id||null}))?.[0];let execution=null;
  if(['approved','adjusted'].includes(decision)){let transfer=null;if(line.action_type==='transfer')transfer=(await insert('transfer_orders',{organization_id:org,workspace_id:ws,sku_id:line.sku_id,from_location_id:fromId,to_location_id:toId,recommended_qty:line.recommended_qty,approved_qty:quantity,status:'approved',reason:{source:'decision_workflow',recommendation_line_id:line.id,decision_id:record.id},approved_by:context.user.id,approved_at:new Date().toISOString(),recommendation_line_id:line.id}))?.[0];const executionNo=`VIIM-${line.action_type.slice(0,2).toUpperCase()}-${new Date().toISOString().slice(2,10).replace(/-/g,'')}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;execution=(await insert('execution_requests',{organization_id:org,workspace_id:ws,decision_id:record.id,transfer_order_id:transfer?.id||null,execution_no:executionNo,execution_type:line.action_type,requested_qty:quantity,status:'requested',metadata:{requested_execution_date:body.requestedExecutionDate||null}}))?.[0];await insert('execution_events',{organization_id:org,workspace_id:ws,execution_request_id:execution.id,event_type:'requested',previous_status:null,next_status:'requested',quantity,source_type:'user',actor_user_id:context.user.id})}
  await audit(context,'recommendation.decision_recorded','recommendation_decision',String(record.id),{recommendationLineId:line.id,decision,quantity,executionId:execution?.id||null});return json({ok:true,decision:record,execution,simulation:expected});
}
async function executionEvent(context:any,body:any){
  requirePagePermission(context,'execution','update');const org=context.membership.organization_id,ws=workspaceId(context),id=String(body.executionRequestId||''),execution=(await list('execution_requests',context,'*',{id:`eq.${id}`,limit:'1'}))[0];if(!execution)return json({ok:false,error:'Execution request not found'},404);const eventType=String(body.eventType||'');if(!(eventType in statusByEvent))return json({ok:false,error:'Invalid execution event'},400);const previous=execution.status,next=statusByEvent[eventType]||previous,quantity=Math.max(0,Number(body.quantity??(eventType==='received'?execution.requested_qty:execution.executed_qty)??0)),values:any={status:next,updated_at:new Date().toISOString()};if(['dispatched','in_transit'].includes(eventType))values.executed_qty=quantity;if(['partially_received','received'].includes(eventType))values.received_qty=quantity;if(next==='in_progress'&&!execution.started_at)values.started_at=new Date().toISOString();if(next==='completed')values.completed_at=new Date().toISOString();if(next==='failed')values.failure_reason=body.note||'실행 실패';const verification=verificationByEvent[eventType];if(verification){values.verification_method=verification[0];values.verification_confidence=verification[1]}
  const updated=(await update('execution_requests',{id:`eq.${id}`,organization_id:`eq.${org}`},values))?.[0];await insert('execution_events',{organization_id:org,workspace_id:ws,execution_request_id:id,event_type:eventType,previous_status:previous,next_status:next,quantity,source_type:body.sourceType||'user',external_reference:body.externalReference||null,evidence:{note:body.note||null},actor_user_id:context.user.id});if(next==='completed'&&execution.transfer_order_id)await update('transfer_orders',{id:`eq.${execution.transfer_order_id}`,organization_id:`eq.${org}`},{status:'received'});if(verification)await update('recommendation_outcomes',{execution_request_id:`eq.${id}`,organization_id:`eq.${org}`},{verification_method:verification[0],learning_eligible:verification[0]!=='inferred'});
  if(next==='completed'){const decision=(await list('recommendation_decisions',context,'recommendation_line_id',{id:`eq.${execution.decision_id}`,limit:'1'}))[0],start=new Date(values.completed_at),eligible=['manual','file_reconciled','api_confirmed'].includes(String(updated.verification_method));for(const days of [7,14,28]){const end=new Date(start);end.setUTCDate(end.getUTCDate()+days);await insert('recommendation_outcomes',{organization_id:org,workspace_id:ws,recommendation_line_id:decision.recommendation_line_id,execution_request_id:id,transfer_order_id:execution.transfer_order_id,measurement_start_date:start.toISOString().slice(0,10),measurement_end_date:end.toISOString().slice(0,10),baseline_method:'pre_execution_28d_internal',executed_qty:Number(updated.received_qty||updated.executed_qty||0),outcome_status:'pending',verification_method:updated.verification_method,learning_eligible:eligible},{upsert:true,onConflict:'recommendation_line_id,measurement_start_date,measurement_end_date'})}}
  await audit(context,'execution.event_recorded','execution_request',id,{eventType,previousStatus:previous,nextStatus:next,quantity});return json({ok:true,execution:updated});
}
async function reviewPolicyCandidate(context:any,body:any){requirePagePermission(context,'decisions','approve');const org=context.membership.organization_id,ws=workspaceId(context),id=String(body.candidateId||''),candidate=(await list('policy_change_candidates',context,'*',{id:`eq.${id}`,limit:'1'}))[0];if(!candidate)return json({ok:false,error:'Policy candidate not found'},404);const decision=String(body.decision||''),allowed:any={approve:['proposed','approved'],apply:['approved','applied'],reject:['proposed','approved','rejected'],rollback:['applied']};if(!allowed[decision])return json({ok:false,error:'Invalid policy decision'},400);if(!allowed[decision].includes(candidate.status))return json({ok:false,error:`Cannot ${decision} policy in ${candidate.status} status`},409);const status=decision==='approve'?'approved':decision==='apply'?'applied':decision==='rollback'?'expired':'rejected',updated=(await update('policy_change_candidates',{id:`eq.${id}`,organization_id:`eq.${org}`},{status,reviewed_by:context.user.id,reviewed_at:new Date().toISOString(),expected_improvement:decision==='rollback'?{...(candidate.expected_improvement||{}),rollback_reason:String(body.note||'manual_rollback')}:candidate.expected_improvement,updated_at:new Date().toISOString()}))?.[0];await audit(context,`policy_candidate.${status}`,'policy_change_candidate',id,{previousStatus:candidate.status,candidateType:candidate.candidate_type,proposedValue:candidate.proposed_value,reason:body.note||null});return json({ok:true,candidate:updated})}

export default {async fetch(request:Request){try{const context=await requestContext(request),org=context.membership.organization_id;if(request.method==='GET'){requirePagePermission(context,new URL(request.url).searchParams.get('page')==='execution'?'execution':'decisions','view');return json({ok:true,...await workflow(context)})}if(request.method!=='POST')return json({ok:false,error:'Method not allowed'},405);const body=await bodyJson(request)||{},action=String(body.action||'');if(action==='simulate'){requirePagePermission(context,'decisions','view');const line=await recommendation(context,String(body.recommendationLineId||''));if(!line)return json({ok:false,error:'Recommendation not found'},404);return json({ok:true,simulation:effectFor(line,Math.max(0,Number(body.quantity??line.recommended_qty)))})}if(action==='decide')return decide(context,body);if(action==='execution_event')return executionEvent(context,body);if(action==='review_policy')return reviewPolicyCandidate(context,body);return json({ok:false,error:'Unsupported action'},400)}catch(error:any){return errorResponse(error,error.status||500)}}};
