import {bodyJson,errorResponse,json} from '../http.js';
import {audit,insert,requestContext,requireRole,supabase,update,workspaceId} from '../supabase.js';
import {assertAnalyticsRefreshAllowed} from '../reconciliation.js';
import {buildInternalInventoryPlan} from '../inventory-planning-pipeline.js';
import {appliedLearningProfiles} from '../policy-learning.js';

const enc=encodeURIComponent;
async function rows(table:string,organizationId:string,workspace:string,select:string,extra:Record<string,string>={}){
  const result:any[]=[],pageSize=1000;
  for(let offset=0;;offset+=pageSize){const query=new URLSearchParams({organization_id:`eq.${organizationId}`,workspace_id:`eq.${workspace}`,select,...extra}),page=(await supabase(`/rest/v1/${table}?${query}`,{serviceRole:true,headers:{Range:`${offset}-${offset+pageSize-1}`,'Range-Unit':'items'}})).data||[];result.push(...page);if(page.length<pageSize)break}return result;
}
async function upsertBatches(table:string,data:any[],organizationId:string,workspace:string,onConflict:string){for(let index=0;index<data.length;index+=500)await insert(table,data.slice(index,index+500).map(row=>({organization_id:organizationId,workspace_id:workspace,...row})),{upsert:true,onConflict})}

export default {async fetch(request:Request){
  if(request.method!=='POST')return json({ok:false,error:'Method not allowed'},405);
  let run:any=null,context:any=null;
  try{
    context=await requestContext(request);requireRole(context,['owner','admin']);const organizationId=context.membership.organization_id,workspace=workspaceId(context);if(!workspace)return json({ok:false,error:'Workspace is required'},400);await assertAnalyticsRefreshAllowed(organizationId,workspace);const body=await bodyJson(request)||{},asOfDate=/^\d{4}-\d{2}-\d{2}$/.test(String(body.asOfDate||''))?String(body.asOfDate):new Date().toISOString().slice(0,10),historyDays=Math.min(90,Math.max(28,Number(body.historyDays)||28)),horizonDays=Math.min(28,Math.max(1,Number(body.horizonDays)||7)),start=new Date(`${asOfDate}T00:00:00Z`);start.setUTCDate(start.getUTCDate()-historyDays);
    run=(await insert('analytics_refresh_runs',{organization_id:organizationId,workspace_id:workspace,pipeline:'inventory_planning_internal',scope_date:asOfDate,status:'running'}))?.[0];
    const [orders,salesLines,snapshots,inboundOrders,inboundLines,transfers,policies,routes,policyCandidates]=await Promise.all([
      rows('sales_orders',organizationId,workspace,'id,location_id,ordered_at,status',{ordered_at:`gte.${start.toISOString()}`}),rows('sales_order_lines',organizationId,workspace,'order_id,sku_id,quantity,returned_quantity,unit_sale_price,unit_cost'),rows('inventory_snapshots',organizationId,workspace,'sku_id,location_id,snapshot_at,on_hand_qty,reserved_qty,available_qty,damaged_qty,safety_stock_qty',{order:'snapshot_at.desc'}),rows('inbound_orders',organizationId,workspace,'id,destination_location_id,status,expected_at'),rows('inbound_order_lines',organizationId,workspace,'inbound_order_id,sku_id,ordered_qty,received_qty,cancelled_qty'),rows('transfer_orders',organizationId,workspace,'sku_id,from_location_id,to_location_id,recommended_qty,approved_qty,status'),rows('inventory_policies',organizationId,workspace,'*'),rows('logistics_routes',organizationId,workspace,'*'),rows('policy_change_candidates',organizationId,workspace,'*',{status:'eq.applied'})
    ]);
    const learningProfiles=appliedLearningProfiles(policyCandidates),watermark=[...orders.map(row=>row.ordered_at),...snapshots.map(row=>row.snapshot_at)].filter(Boolean).sort().at(-1)||new Date().toISOString(),plan=buildInternalInventoryPlan({asOfDate,historyDays,horizonDays,workspaceId:workspace,orders,lines:salesLines,snapshots,inboundOrders,inboundLines,transfers,policies,routes,learningProfiles,budgetAmount:body.budgetAmount,minNetValue:body.minNetValue,limit:body.limit});
    const stampedPositions=plan.positions.map(row=>({...row,source_watermark:watermark})),stampedForecasts=plan.forecasts.map(row=>({...row,input_watermark:watermark}));await upsertBatches('inventory_positions_daily',stampedPositions,organizationId,workspace,'organization_id,workspace_id,position_date,sku_id,location_id,calculation_version');await upsertBatches('demand_forecasts',stampedForecasts,organizationId,workspace,'organization_id,workspace_id,as_of_date,target_date,sku_id,location_id,model_version');
    const scenario=(await insert('recommendation_scenarios',{organization_id:organizationId,workspace_id:workspace,refresh_run_id:run?.id||null,scenario_key:`internal:${asOfDate}:${horizonDays}:${run.id}`,scenario_type:'rebalancing',as_of_date:asOfDate,horizon_days:horizonDays,status:plan.readiness.ready?'ready':'draft',engine_version:'internal-v1',policy_snapshot:{active_rows:plan.readiness.policyRows,learning_profiles:learningProfiles},constraint_snapshot:{route_rows:plan.readiness.routeRows,budget_amount:body.budgetAmount??null,min_net_value:body.minNetValue??0},objective_weights:{net_value:1},summary:{recommendation_count:plan.recommendations.length,readiness:plan.readiness,learning:plan.learning},source_watermark:watermark}))?.[0];
    if(scenario&&plan.recommendations.length)await upsertBatches('recommendation_scenario_lines',plan.recommendations.map((item:any,index:number)=>({scenario_id:scenario.id,recommendation_key:item.recommendationKey,action_type:'transfer',sku_id:item.skuId,from_location_id:item.fromLocationId,to_location_id:item.toLocationId,recommended_qty:item.recommendedQty,pack_rounded_qty:item.recommendedQty,forecast_demand_qty:item.destinationShortageQty,source_excess_qty:item.sourceExcessQty,destination_shortage_qty:item.destinationShortageQty,expected_margin_gain:item.expectedMarginGain,expected_logistics_cost:item.expectedLogisticsCost,expected_net_value:item.expectedNetValue,rank:index+1,reason_codes:item.reasonCodes,explanation:{destination_cover_days:item.destinationCoverDays}})),organizationId,workspace,'scenario_id,recommendation_key');
    await update('analytics_refresh_runs',{id:`eq.${run.id}`,organization_id:`eq.${organizationId}`},{status:'completed',input_rows:orders.length+salesLines.length+snapshots.length,output_rows:stampedPositions.length+stampedForecasts.length+plan.recommendations.length,source_watermark:watermark,completed_at:new Date().toISOString()});await audit(context,'inventory.planning.refreshed','recommendation_scenario',scenario?.id,{asOfDate,horizonDays,readiness:plan.readiness,positions:stampedPositions.length,forecasts:stampedForecasts.length,recommendations:plan.recommendations.length});return json({ok:true,runId:run.id,scenarioId:scenario?.id,asOfDate,horizonDays,positions:stampedPositions.length,forecasts:stampedForecasts.length,recommendations:plan.recommendations.length,readiness:plan.readiness});
  }catch(error:any){if(run&&context)await update('analytics_refresh_runs',{id:`eq.${run.id}`,organization_id:`eq.${context.membership.organization_id}`},{status:'failed',error_message:String(error.message||error).slice(0,1000),completed_at:new Date().toISOString()}).catch(()=>null);return errorResponse(error,error.status||500)}
}};
