import {bodyJson,errorResponse,json} from '../http.js';
import {requireAttentionTransition,resolutionRequirements} from '../operational-workflow.js';
import {filterProviderScope,inProviderScope,providerAudit,providerContext,requireProviderPermission} from '../provider-admin.js';
import {insert,supabase,update} from '../supabase.js';

async function rows(table:string,params:Record<string,string>){return (await supabase(`/rest/v1/${table}?${new URLSearchParams(params)}`,{serviceRole:true})).data||[]}
export default {async fetch(request:Request){try{
  const context=await providerContext(request);requireProviderPermission(context,request.method==='GET'?'portfolio.view':'attention.manage');const url=new URL(request.url);
  if(request.method==='GET'){const limit=Math.min(200,Math.max(1,Number(url.searchParams.get('limit'))||50)),params:any={select:'*',order:'detected_at.desc',limit:String(limit)};if(url.searchParams.get('status'))params.status=`eq.${url.searchParams.get('status')}`;if(url.searchParams.get('severity'))params.severity=`eq.${url.searchParams.get('severity')}`;return json({ok:true,items:filterProviderScope(context,await rows('attention_items',params))})}
  if(request.method!=='POST')return json({ok:false,error:'Method not allowed'},405);const body:any=await bodyJson(request);if(!body?.id||!body?.action)return json({ok:false,error:'id and action are required'},400);const item=(await rows('attention_items',{id:`eq.${body.id}`,select:'*',limit:'1'}))[0];if(!item)return json({ok:false,error:'Attention item not found'},404);if(!inProviderScope(context,item))return json({ok:false,error:'Attention item is outside the provider scope'},403);let result:any=item;
  if(body.action==='assign'){result=(await update('attention_items',{id:`eq.${item.id}`},{assigned_team:body.assigned_team||item.assigned_team,assigned_user_id:body.assigned_user_id||null,updated_at:new Date().toISOString()}))?.[0]}
  else if(body.action==='acknowledge'){requireAttentionTransition(item.status,'acknowledged');result=(await update('attention_items',{id:`eq.${item.id}`},{status:'acknowledged',acknowledged_at:new Date().toISOString(),updated_at:new Date().toISOString()}))?.[0]}
  else if(body.action==='start'){requireAttentionTransition(item.status,'in_progress');result=(await update('attention_items',{id:`eq.${item.id}`},{status:'in_progress',updated_at:new Date().toISOString()}))?.[0];const existing=await rows('operational_tasks',{attention_item_id:`eq.${item.id}`,status:'not.in.(completed,cancelled)',select:'id',limit:'1'});if(!existing.length)await insert('operational_tasks',{organization_id:item.organization_id,workspace_id:item.workspace_id,brand_id:item.brand_id,attention_item_id:item.id,task_type:item.category,priority:item.severity==='critical'?'p1':'p2',status:'in_progress',title:item.title,description:item.summary,assigned_team:item.assigned_team,assigned_user_id:item.assigned_user_id,due_at:item.resolution_due_at||item.sla_due_at,completion_criteria:item.metadata?.completion_criteria||[],metadata:{source_object_type:item.source_object_type,source_object_id:item.source_object_id}})}
  else if(body.action==='resolve'){requireAttentionTransition(item.status,'resolved');const requirements=resolutionRequirements({sourceHealthy:Boolean(body.source_healthy),resolutionNote:body.resolution_note,manualOverride:Boolean(body.manual_override)});if(!requirements.ready)return json({ok:false,error:'Resolution requirements are not satisfied',missing:requirements.missing},409);const activeTasks=await rows('operational_tasks',{attention_item_id:`eq.${item.id}`,status:'not.in.(completed,cancelled)',select:'id,status',limit:'20'});if(activeTasks.length&&!body.manual_override)return json({ok:false,error:'Linked operational tasks must be completed first',tasks:activeTasks},409);result=(await update('attention_items',{id:`eq.${item.id}`},{status:'resolved',resolved_at:new Date().toISOString(),updated_at:new Date().toISOString(),metadata:{...(item.metadata||{}),resolution_note:body.resolution_note,manual_override:Boolean(body.manual_override)}}))?.[0]}
  else return json({ok:false,error:'Unsupported attention action'},400);
  await providerAudit(context,`attention.${body.action}`,'attention_item',item.id,{organization_id:item.organization_id,workspace_id:item.workspace_id,reason:body.reason||body.resolution_note||null,from_status:item.status,to_status:result.status});return json({ok:true,item:result});
}catch(error:any){return errorResponse(error,error.status||500)}}};
