import {bodyJson,errorResponse,json} from '../http.js';
import {evaluateOperationalEvent,eventDedupeKey} from '../operational-workflow.js';
import {filterProviderScope,providerContext,requireProviderPermission} from '../provider-admin.js';
import {insert,supabase,update} from '../supabase.js';

async function rows(table:string,params:Record<string,string>){return (await supabase(`/rest/v1/${table}?${new URLSearchParams(params)}`,{serviceRole:true})).data||[]}
function requireInternalKey(request:Request){const configured=process.env.VIIM_OPERATIONAL_EVENT_KEY;if(!configured){const error:any=new Error('Operational event ingestion is not configured');error.status=503;throw error}if(request.headers.get('x-viim-event-key')!==configured){const error:any=new Error('Invalid operational event key');error.status=401;throw error}}

export default {async fetch(request:Request){try{
  if(request.method==='GET'){const context=await providerContext(request);requireProviderPermission(context,'portfolio.view');const url=new URL(request.url),limit=Math.min(200,Math.max(1,Number(url.searchParams.get('limit'))||50)),events=await rows('operational_events',{select:'id,organization_id,workspace_id,brand_id,event_type,severity,object_type,object_id,correlation_id,dedupe_key,payload,occurred_at,processed_at',order:'occurred_at.desc',limit:String(limit)});return json({ok:true,events:filterProviderScope(context,events)})}
  if(request.method!=='POST')return json({ok:false,error:'Method not allowed'},405);requireInternalKey(request);const body:any=await bodyJson(request);for(const key of ['organization_id','event_type','object_type'])if(!body?.[key])return json({ok:false,error:`${key} is required`},400);
  const dedupeKey=eventDedupeKey(body),existing=await rows('operational_events',{organization_id:`eq.${body.organization_id}`,dedupe_key:`eq.${dedupeKey}`,select:'id,processed_at',limit:'1'});if(existing[0])return json({ok:true,deduplicated:true,eventId:existing[0].id},200);
  const occurredAt=body.occurred_at||new Date().toISOString(),event=(await insert('operational_events',{organization_id:body.organization_id,workspace_id:body.workspace_id||null,brand_id:body.brand_id||null,event_type:body.event_type,severity:body.severity||'warning',object_type:body.object_type,object_id:body.object_id||null,correlation_id:body.correlation_id||null,dedupe_key:dedupeKey,payload:body.payload||{},occurred_at:occurredAt}))?.[0],decision=evaluateOperationalEvent({...body,dedupe_key:dedupeKey},new Date(occurredAt));
  if(!decision.createAttention){await update('operational_events',{id:`eq.${event.id}`},{processed_at:new Date().toISOString()});return json({ok:true,event,attention:null,decision},201)}
  const attention=(await insert('attention_items',{organization_id:body.organization_id,workspace_id:body.workspace_id||null,brand_id:body.brand_id||null,source_event_id:event.id,dedupe_key:decision.dedupeKey,severity:decision.severity,status:'open',category:decision.category,title:decision.title,summary:decision.summary,assigned_team:decision.assignedTeam,response_due_at:decision.responseDueAt,resolution_due_at:decision.resolutionDueAt,sla_due_at:decision.responseDueAt,detected_at:occurredAt,source_object_type:body.object_type,source_object_id:body.object_id||null,metadata:{completion_criteria:decision.completionCriteria,decision}}))?.[0];let incident=null;
  if(decision.incident){incident=(await insert('incidents',{organization_id:body.organization_id,workspace_id:body.workspace_id||null,source_attention_item_id:attention.id,incident_key:`INC-${dedupeKey}`.slice(0,120),severity:decision.incident,status:'investigating',title:decision.title,summary:decision.summary,affected_organization_ids:[body.organization_id],affected_workspace_ids:body.workspace_id?[body.workspace_id]:[],affected_features:body.payload?.affected_features||[],next_update_at:decision.responseDueAt,metadata:{source_event_id:event.id}}))?.[0]}
  await update('operational_events',{id:`eq.${event.id}`},{processed_at:new Date().toISOString()});return json({ok:true,event,attention,incident,decision},201);
}catch(error:any){return errorResponse(error,error.status||500)}}};
