import {bodyJson,errorResponse,json} from '../http.js';
import {filterProviderScope,inProviderScope,providerAudit,providerContext,requireProviderPermission} from '../provider-admin.js';
import {insert,supabase,update} from '../supabase.js';

async function rows(params:Record<string,string>){return (await supabase(`/rest/v1/incidents?${new URLSearchParams(params)}`,{serviceRole:true})).data||[]}
const transitions:any={investigating:['identified','monitoring','resolved'],identified:['monitoring','resolved'],monitoring:['identified','resolved'],resolved:['closed'],closed:[]};
export default {async fetch(request:Request){try{
  const context=await providerContext(request);requireProviderPermission(context,request.method==='GET'?'portfolio.view':'attention.manage');const url=new URL(request.url);
  if(request.method==='GET'){const incidents=await rows({select:'*',order:'started_at.desc',limit:String(Math.min(200,Math.max(1,Number(url.searchParams.get('limit'))||50)))});return json({ok:true,incidents:context.provider.role==='super_admin'?incidents:filterProviderScope(context,incidents)})}
  if(request.method!=='POST')return json({ok:false,error:'Method not allowed'},405);const body:any=await bodyJson(request);if(!body?.id||!body?.status)return json({ok:false,error:'id and status are required'},400);const incident=(await rows({id:`eq.${body.id}`,select:'*',limit:'1'}))[0];if(!incident)return json({ok:false,error:'Incident not found'},404);if(context.provider.role!=='super_admin'&&!inProviderScope(context,incident))return json({ok:false,error:'Incident is outside the provider scope'},403);if(!transitions[incident.status]?.includes(body.status))return json({ok:false,error:`Invalid incident transition: ${incident.status} -> ${body.status}`},409);const now=new Date().toISOString(),values:any={status:body.status,updated_at:now};if(body.customer_message!==undefined)values.customer_message=body.customer_message;if(body.next_update_at!==undefined)values.next_update_at=body.next_update_at;if(body.status==='resolved')values.resolved_at=now;const result=(await update('incidents',{id:`eq.${incident.id}`},values))?.[0];await insert('incident_updates',{incident_id:incident.id,status:body.status,internal_note:body.internal_note||null,customer_message:body.customer_message||null,created_by:context.user.id});await providerAudit(context,'incident.updated','incident',incident.id,{organization_id:incident.organization_id,workspace_id:incident.workspace_id,reason:body.internal_note||null,from_status:incident.status,to_status:body.status});return json({ok:true,incident:result});
}catch(error:any){return errorResponse(error,error.status||500)}}};
