import {bodyJson,errorResponse,json} from '../_lib/http.js';
import {buildDecisionActions,summarizeDecisionActions} from '../_lib/decision-actions.js';
import {summarizeCustomerInsights,summarizeReturnInsights} from '../_lib/customer-returns.js';
import {buildTransferCandidates,nextMovementStatus,summarizeInventorySnapshot} from '../_lib/inventory-operations.js';
import {MARKET_DIMENSIONS,MARKET_METRICS,normalizeQuerySpec} from '../_lib/semantic.js';
import {audit,insert,requestContext,requirePagePermission,requireRole,scopedValues,supabase,update} from '../_lib/supabase.js';
import {assertAnalyticsRefreshAllowed} from '../_lib/reconciliation.js';

export async function runDashboardQuery(context:any,input:any){
  const spec=normalizeQuerySpec(input);const isMarket=MARKET_METRICS.includes(spec.metric)||MARKET_DIMENSIONS.includes(spec.dimension);if(['available_qty','inventory_cover_days','sell_through_rate'].includes(spec.metric)&&!['product','location'].includes(spec.dimension))spec.dimension='product';const end=new Date();const start=new Date(end.getTime()-spec.periodDays*86400000);
  if(isMarket){if(!MARKET_METRICS.includes(spec.metric))spec.metric='exposure_score';if(!['brand','platform','day','category','market_product'].includes(spec.dimension))spec.dimension='brand';const payload={p_organization_id:context.membership.organization_id,p_page_key:String(input.page||'market'),p_metric:spec.metric,p_dimension:spec.dimension,p_start:start.toISOString().slice(0,10),p_end:end.toISOString().slice(0,10),p_platform:spec.filters.platform||null,p_limit:spec.limit};const data=(await supabase('/rest/v1/rpc/query_market_dashboard',{method:'POST',token:context.accessToken,body:payload})).data;return {spec,data}}
  const payload={p_organization_id:context.membership.organization_id,p_page_key:String(input.page||'hub'),p_metric:spec.metric,p_dimension:spec.dimension,p_start:start.toISOString(),p_end:end.toISOString(),p_countries:scopedValues(context,'countries',spec.filters.country),p_channels:scopedValues(context,'channels',spec.filters.channel),p_locations:scopedValues(context,'locations')};
  const data=(await supabase('/rest/v1/rpc/query_sales_dashboard',{method:'POST',token:context.accessToken,body:payload})).data;
  return {spec,data};
}

async function overviewRows(context:any,page:string,metric:string,dimension:string,periodDays:number){return (await runDashboardQuery(context,{page,metric,dimension,periodDays,visualization:dimension==='day'?'area':'bar',limit:30,filters:{}})).data?.rows||[]}
const sum=(rows:any[],key:string)=>rows.reduce((total,row)=>total+Number(row[key]||0),0);
export function summarizeProfitabilityReadiness(rows:any[]=[]){
  const total=rows.length,costCovered=rows.filter(row=>Number(row.unit_cost||0)>0).length,variableCostCovered=rows.filter(row=>['channel_fee','marketing_cost','shipping_cost','return_cost'].some(key=>Number(row[key]||0)>0)).length;
  const pct=(value:number)=>total?Math.round(value/total*1000)/10:0;
  return {totalLines:total,costCoveredLines:costCovered,variableCostCoveredLines:variableCostCovered,costCoveragePct:pct(costCovered),variableCostCoveragePct:pct(variableCostCovered),ready:total>0&&pct(costCovered)>=80&&pct(variableCostCovered)>=50};
}
async function profitabilitySummary(context:any){
  requirePagePermission(context,'profitability','view');const org=context.membership.organization_id;
  const [channels,products,costResult]=await Promise.all([
    overviewRows(context,'profitability','contribution_margin','channel',60),overviewRows(context,'profitability','contribution_margin','product',60),
    supabase(`/rest/v1/sales_order_lines?organization_id=eq.${enc(org)}&select=unit_cost,channel_fee,marketing_cost,shipping_cost,return_cost&order=created_at.desc&limit=10000`,{serviceRole:true})
  ]);
  const readiness=summarizeProfitabilityReadiness(costResult.data||[]),netSales=sum(channels,'net_sales'),contributionMargin=sum(channels,'contribution_margin');
  return {generatedAt:new Date().toISOString(),periodDays:60,readiness,summary:{netSales,contributionMargin,costs:Math.max(0,netSales-contributionMargin),marginRate:netSales?contributionMargin/netSales*100:0},channels,products};
}
export function latestForecastRows(rows:any[]=[]){const seen=new Set<string>();return rows.filter(row=>{const prediction=row.predictions||row,key=String(prediction.product_code||prediction.product_id||row.subject_key||'');if(!key||seen.has(key))return false;seen.add(key);return true}).map(row=>({...row.predictions,confidence:row.confidence,as_of_date:row.as_of_date,horizon_days:row.horizon_days,generated_at:row.generated_at}))}
export function planningReorderQuantity(row:any,leadTimeDays=14){const horizon=Math.max(1,Number(row.horizon_days||28)),forecast=Math.max(0,Number(row.forecast_quantity||0)),available=Math.max(0,Number(row.available_qty||0)),safety=Math.max(0,Number(row.safety_stock_qty||0)),stored=Math.max(0,Number(row.recommended_reorder_qty||0)),daily=forecast/horizon,planning=Math.round(Math.max(0,daily*(horizon+Math.max(0,leadTimeDays))+safety-available));return Math.max(stored,planning)}
async function productIntelligence(context:any,page='market',limit=30){const data=(await supabase('/rest/v1/rpc/query_product_intelligence',{method:'POST',token:context.accessToken,body:{p_organization_id:context.membership.organization_id,p_page_key:page,p_limit:Math.min(100,Math.max(1,limit))}})).data;if(data?.forecasts){const seen=new Set<string>();data.forecasts=data.forecasts.filter((row:any)=>{const key=String(row.product_code||'');if(!key||seen.has(key))return false;seen.add(key);return true})}return data}
async function discountIntelligence(context:any,page='profitability',limit=40){return (await supabase('/rest/v1/rpc/query_discount_recommendations',{method:'POST',token:context.accessToken,body:{p_organization_id:context.membership.organization_id,p_page_key:page,p_limit:Math.min(100,Math.max(1,limit))}})).data}
const enc=(value:string)=>encodeURIComponent(value);
const indexBy=(rows:any[],key='id')=>new Map(rows.map(row=>[String(row[key]),row]));
async function inventoryWorkflowContext(context:any){
  const org=context.membership.organization_id,q=enc(org);
  const [transfers,movements,snapshots,skus,products,locations,forecasts,recommendations]=await Promise.all([
    supabase(`/rest/v1/transfer_orders?organization_id=eq.${q}&select=*&order=created_at.desc&limit=100`,{serviceRole:true}),supabase(`/rest/v1/inventory_movements?organization_id=eq.${q}&select=*&order=occurred_at.desc&limit=100`,{serviceRole:true}),latestInventorySnapshots(org,1000),supabase(`/rest/v1/skus?organization_id=eq.${q}&select=id,sku_code,product_id,size,color&limit=1000`,{serviceRole:true}),supabase(`/rest/v1/products?organization_id=eq.${q}&select=id,product_code,product_name,image_url&limit=1000`,{serviceRole:true}),supabase(`/rest/v1/locations?organization_id=eq.${q}&select=id,location_code,location_name,location_type,country_code&limit=1000`,{serviceRole:true}),supabase(`/rest/v1/forecast_snapshots?organization_id=eq.${q}&target_metric=eq.quantity&subject_type=eq.product&select=subject_key,predictions,confidence,as_of_date,horizon_days,generated_at&order=generated_at.desc&limit=500`,{serviceRole:true}),supabase(`/rest/v1/ax_recommendations?organization_id=eq.${q}&page_key=eq.inventory&select=id,recommendation_key,title,status,payload,approved_at,created_at,updated_at&order=updated_at.desc&limit=100`,{serviceRole:true})
  ]);
  return {org,transfers:transfers.data||[],movements:movements.data||[],snapshots:snapshots.data||[],skus:skus.data||[],products:products.data||[],locations:locations.data||[],forecasts:latestForecastRows(forecasts.data||[]),recommendations:recommendations.data||[]};
}
async function latestInventorySnapshots(org:string,limit=10000){
  const jobQuery=new URLSearchParams({organization_id:`eq.${org}`,entity_type:'eq.inventory_snapshot',status:'in.(completed,partial)',select:'id,raw_upload_id,completed_at,created_at',order:'created_at.desc',limit:'1'}),jobs=(await supabase(`/rest/v1/import_jobs?${jobQuery}`,{serviceRole:true})).data||[],job=jobs[0],snapshotQuery=new URLSearchParams({organization_id:`eq.${org}`,select:'sku_id,location_id,snapshot_at,on_hand_qty,reserved_qty,available_qty',limit:String(limit)});
  if(!job?.raw_upload_id)return supabase(`/rest/v1/inventory_snapshots?${snapshotQuery}`,{serviceRole:true});
  snapshotQuery.set('raw_upload_id',`eq.${job.raw_upload_id}`);
  const result=await supabase(`/rest/v1/inventory_snapshots?${snapshotQuery}`,{serviceRole:true});
  return {...result,importJob:job,readMode:'latest_import'};
}
async function customerReturnContext(context:any){
  const org=context.membership.organization_id,q=enc(org),end=new Date(),start=new Date(end.getTime()-90*86400000),[ordersResult,linesResult,productsResult,locationsResult]=await Promise.all([
    supabase(`/rest/v1/sales_orders?organization_id=eq.${q}&ordered_at=gte.${encodeURIComponent(start.toISOString())}&ordered_at=lt.${encodeURIComponent(end.toISOString())}&select=id,channel_code,location_id,ordered_at,status,country_code,paid_amount,customer_token,shipping_region_1,shipping_region_2&order=ordered_at.desc&limit=20000`,{serviceRole:true}),
    supabase(`/rest/v1/sales_order_lines?organization_id=eq.${q}&select=order_id,sku_id,product_id,quantity,returned_quantity,net_sales,unit_list_price,return_cost&limit=50000`,{serviceRole:true}),
    supabase(`/rest/v1/products?organization_id=eq.${q}&select=id,product_code,product_name,image_url&limit=5000`,{serviceRole:true}),
    supabase(`/rest/v1/locations?organization_id=eq.${q}&select=id,location_code,country_code&limit=5000`,{serviceRole:true})
  ]),locationMap=indexBy(locationsResult.data||[]),countries=scopedValues(context,'countries'),channels=scopedValues(context,'channels'),locations=scopedValues(context,'locations'),orders=(ordersResult.data||[]).filter((row:any)=>{const location:any=locationMap.get(String(row.location_id))||{};return (!countries||countries.includes(String(row.country_code||location.country_code||'')))&&(!channels||channels.includes(String(row.channel_code||'')))&&(!locations||locations.includes(String(location.location_code||'')))}),orderIds=new Set(orders.map((row:any)=>String(row.id))),lines=(linesResult.data||[]).filter((row:any)=>orderIds.has(String(row.order_id)));
  return {orders,lines,products:productsResult.data||[],periodDays:90};
}
export async function customerReturnInsights(context:any){
  const data=await customerReturnContext(context);
  return {periodDays:data.periodDays,customer:summarizeCustomerInsights(data.orders),returns:summarizeReturnInsights(data.orders,data.lines,data.products)};
}
function presentInventoryWorkflow(data:any){
  const skuMap=indexBy(data.skus),productMap=indexBy(data.products),locationMap=indexBy(data.locations),recommendationMap=new Map<string,any>();for(const row of data.recommendations)if(!recommendationMap.has(row.recommendation_key))recommendationMap.set(row.recommendation_key,row);
  const labelSku=(skuId:string)=>{const sku:any=skuMap.get(String(skuId))||{},product:any=productMap.get(String(sku.product_id))||{};return {...sku,product_code:product.product_code||sku.sku_code||'SKU',product_name:product.product_name||product.product_code||sku.sku_code||'상품',image_url:product.image_url||null}},labelLocation=(locationId:string)=>locationMap.get(String(locationId))||{location_code:'UNKNOWN',location_name:'위치 미확인'};
  const transfers=[...data.transfers,...buildTransferCandidates(data.snapshots,data.transfers)].map((row:any)=>({...row,sku:labelSku(row.sku_id),from_location:labelLocation(row.from_location_id),to_location:labelLocation(row.to_location_id),persisted:Boolean(row.id)})),reorders=data.forecasts.map((row:any)=>({...row,recommended_reorder_qty:planningReorderQuantity(row),planning_lead_time_days:14})).filter((row:any)=>Number(row.recommended_reorder_qty||0)>0).map((row:any)=>{const stored=recommendationMap.get(`reorder:${row.product_code}`);return {...row,recommendation_id:stored?.id||null,status:stored?.status||'proposed',approved_at:stored?.approved_at||null}}),shipments=data.movements.filter((row:any)=>['transfer','inbound','outbound'].includes(String(row.movement_type||''))).map((row:any)=>({...row,sku:labelSku(row.sku_id),from_location:row.from_location_id?labelLocation(row.from_location_id):null,to_location:row.to_location_id?labelLocation(row.to_location_id):null,next_status:nextMovementStatus(String(row.status||''))}));
  return {transfers,reorders,shipments,summary:{transferProposals:transfers.filter((row:any)=>row.status==='recommended').length,approvedTransfers:transfers.filter((row:any)=>row.status==='approved').length,reorderProposals:reorders.filter((row:any)=>row.status!=='approved').length,shipmentRisks:shipments.filter((row:any)=>row.status==='delayed').length,forecastHorizon:Math.max(0,...data.forecasts.map((row:any)=>Number(row.horizon_days||0)))}};
}
async function assertInventoryMaster(context:any,table:string,id:string){const org=context.membership.organization_id,rows=(await supabase(`/rest/v1/${table}?id=eq.${enc(id)}&organization_id=eq.${enc(org)}&select=id&limit=1`,{serviceRole:true})).data||[];if(!rows.length){const error:any=new Error(`${table} record not found`);error.status=404;throw error}}
async function approveInventoryTransfer(context:any,body:any){
  requirePagePermission(context,'inventory','approve');const org=context.membership.organization_id,qty=Math.floor(Number(body.approvedQty||body.recommendedQty||0));if(!body.skuId||!body.fromLocationId||!body.toLocationId||qty<=0)return json({ok:false,error:'SKU, locations and approved quantity are required'},400);await Promise.all([assertInventoryMaster(context,'skus',String(body.skuId)),assertInventoryMaster(context,'locations',String(body.fromLocationId)),assertInventoryMaster(context,'locations',String(body.toLocationId))]);const now=new Date().toISOString();let transfer:any;
  if(body.transferOrderId){const rows=await update('transfer_orders',{id:`eq.${body.transferOrderId}`,organization_id:`eq.${org}`},{approved_qty:qty,status:'approved',approved_by:context.user.id,approved_at:now});transfer=rows?.[0];if(!transfer)return json({ok:false,error:'Transfer order not found'},404)}else transfer=(await insert('transfer_orders',{organization_id:org,sku_id:body.skuId,from_location_id:body.fromLocationId,to_location_id:body.toLocationId,recommended_qty:Number(body.recommendedQty||qty),approved_qty:qty,status:'approved',reason:body.reason||{source:'inventory_dashboard'},approved_by:context.user.id,approved_at:now}))?.[0];
  const movement=(await insert('inventory_movements',{organization_id:org,source_movement_id:`transfer:${transfer.id}`,sku_id:transfer.sku_id,from_location_id:transfer.from_location_id,to_location_id:transfer.to_location_id,movement_type:'transfer',quantity:qty,occurred_at:now,status:'approved',reference_no:`TR-${String(transfer.id).slice(0,8).toUpperCase()}`}))?.[0];await audit(context,'inventory.transfer.approved','transfer_order',transfer.id,{quantity:qty,movementId:movement?.id});return json({ok:true,transfer,movement});
}
async function approveInventoryReorder(context:any,body:any){
  requirePagePermission(context,'inventory','approve');const org=context.membership.organization_id,productCode=String(body.productCode||''),qty=Math.floor(Number(body.quantity||0));if(!productCode||qty<=0)return json({ok:false,error:'Product and reorder quantity are required'},400);const now=new Date().toISOString(),forecast=body.forecast||{},dueDate=new Date(Date.now()+21*86400000).toISOString().slice(0,10),conversation=(await insert('ax_conversations',{organization_id:org,user_id:context.user.id,title:`${productCode} 재주문 승인`,page_key:'inventory',status:'active'}))?.[0],recommendation=(await insert('ax_recommendations',{organization_id:org,conversation_id:conversation.id,recommendation_key:`reorder:${productCode}`,page_key:'inventory',title:`${productCode} ${qty.toLocaleString()}pcs 재주문`,status:'approved',payload:{kind:'reorder',product_code:productCode,product_name:forecast.product_name||productCode,quantity:qty,forecast,production_order_no:`PO-${new Date().toISOString().slice(2,10).replace(/-/g,'')}-${productCode.replace(/[^A-Z0-9]/gi,'').slice(0,6)}`,production_status:'approved',progress:0,factory:'미배정',due_date:dueDate},created_by:context.user.id,approved_by:context.user.id,approved_at:now,updated_at:now}))?.[0];await insert('ax_action_events',{organization_id:org,recommendation_id:recommendation.id,conversation_id:conversation.id,actor_user_id:context.user.id,action:'approved',payload:{kind:'reorder',quantity:qty,production_status:'approved'}});await audit(context,'inventory.reorder.approved','ax_recommendation',recommendation.id,{productCode,quantity:qty,dueDate,productionQueue:true});return json({ok:true,recommendation});
}
async function updateInventoryShipment(context:any,body:any){const status=String(body.status||'');if(!['in_transit','received','delayed'].includes(status))return json({ok:false,error:'Valid shipment status is required'},400);requirePagePermission(context,'inventory',status==='received'?'approve':'update');const org=context.membership.organization_id,rows=await update('inventory_movements',{id:`eq.${body.movementId}`,organization_id:`eq.${org}`},{status,occurred_at:new Date().toISOString()}),movement=rows?.[0];if(!movement)return json({ok:false,error:'Shipment not found'},404);await audit(context,`inventory.shipment.${status}`,'inventory_movement',movement.id,{from:body.previousStatus||null});return json({ok:true,movement})}
const productionStages:any={approved:0,planning:10,materials:25,cutting:42,sewing:68,inspection:88,completed:100,held:0};
function productionOrdersFromRecommendations(recommendations:any[]=[],products:any[]=[]){
  const productMap=new Map(products.map((row:any)=>[String(row.product_code),row])),seen=new Set<string>();
  return recommendations.filter((row:any)=>row.payload?.kind==='reorder').filter((row:any)=>{const key=String(row.payload?.product_code||row.recommendation_key);if(seen.has(key))return false;seen.add(key);return true}).map((row:any)=>{const payload=row.payload||{},forecast=payload.forecast||{},product:any=productMap.get(String(payload.product_code))||{};return {id:row.id,conversation_id:row.conversation_id,production_order_no:payload.production_order_no||`PO-${String(row.id).slice(0,8).toUpperCase()}`,product_code:payload.product_code||row.recommendation_key.replace(/^reorder:/,''),product_name:payload.product_name||product.product_name||payload.product_code,image_url:product.image_url||null,quantity:Number(payload.quantity||0),forecast_quantity:Number(forecast.forecast_quantity||0),forecast_net_sales:Number(forecast.forecast_net_sales||0),available_qty:Number(forecast.available_qty||0),confidence:Number(forecast.confidence||0),horizon_days:Number(forecast.horizon_days||28),production_status:payload.production_status||'approved',progress:Number(payload.progress??(productionStages[payload.production_status||'approved']||0)),factory:payload.factory||'미배정',due_date:payload.due_date||null,approved_at:row.approved_at,updated_at:row.updated_at}});
}
async function productionWorkflow(context:any){
  requirePagePermission(context,'production','view');const org=context.membership.organization_id,q=enc(org),[recommendations,products]=await Promise.all([supabase(`/rest/v1/ax_recommendations?organization_id=eq.${q}&page_key=eq.inventory&select=id,conversation_id,recommendation_key,title,status,payload,approved_at,created_at,updated_at&order=updated_at.desc&limit=200`,{serviceRole:true}),supabase(`/rest/v1/products?organization_id=eq.${q}&select=id,product_code,product_name,image_url&limit=1000`,{serviceRole:true})]);
  const orders=productionOrdersFromRecommendations(recommendations.data||[],products.data||[]);
  return {orders,summary:{total:orders.length,totalQuantity:orders.reduce((n:number,row:any)=>n+row.quantity,0),inProgress:orders.filter((row:any)=>!['approved','completed','held'].includes(row.production_status)).length,completed:orders.filter((row:any)=>row.production_status==='completed').length,protectedSales:orders.reduce((n:number,row:any)=>n+row.forecast_net_sales,0)}};
}
async function updateProductionOrder(context:any,body:any){
  requirePagePermission(context,'production','update');const status=String(body.status||''),allowed=Object.keys(productionStages);if(!allowed.includes(status))return json({ok:false,error:'Valid production status is required'},400);const org=context.membership.organization_id,id=String(body.recommendationId||''),query=new URLSearchParams({id:`eq.${id}`,organization_id:`eq.${org}`,select:'id,conversation_id,status,payload',limit:'1'}),existing=((await supabase(`/rest/v1/ax_recommendations?${query}`,{serviceRole:true})).data||[])[0];if(!existing||existing.payload?.kind!=='reorder')return json({ok:false,error:'Production order not found'},404);const payload={...existing.payload,production_status:status,progress:productionStages[status],factory:body.factory||existing.payload.factory||'미배정',due_date:body.dueDate||existing.payload.due_date||null,last_production_update:new Date().toISOString()},recommendationStatus=status==='completed'?'executed':status==='held'?'held':'approved',rows=await update('ax_recommendations',{id:`eq.${id}`,organization_id:`eq.${org}`},{status:recommendationStatus,payload,updated_at:new Date().toISOString()}),eventAction=status==='completed'?'executed':status==='held'?'held':'approved';await insert('ax_action_events',{organization_id:org,recommendation_id:id,conversation_id:existing.conversation_id,actor_user_id:context.user.id,action:eventAction,payload:{kind:'production_status',from:existing.payload.production_status||'approved',to:status,progress:productionStages[status]}});await audit(context,`production.order.${status}`,'ax_recommendation',id,{from:existing.payload.production_status||'approved',to:status,progress:productionStages[status]});return json({ok:true,recommendation:rows?.[0]})
}

function canAccessPage(context:any,page:string,action:'view'|'update'|'approve'='view'){
  if(['owner','admin'].includes(context.membership.role))return true;
  const permission=context.permissions.find((item:any)=>item.page_key===page),field=action==='view'?'can_view':action==='update'?'can_update':'can_approve';
  return Boolean(permission?.[field]);
}

async function decisionActionContext(context:any){
  requirePagePermission(context,'action','view');
  const org=context.membership.organization_id,q=enc(org),[inventory,customerReturns]=await Promise.all([inventoryWorkflowContext(context),customerReturnInsights(context).catch(()=>({customer:null,returns:null}))]),presented=presentInventoryWorkflow(inventory);
  const [discountResult,persistedResult]=await Promise.all([
    discountIntelligence(context,'action',40).catch(()=>({recommendations:[]})),
    supabase(`/rest/v1/ax_recommendations?organization_id=eq.${q}&page_key=eq.action&select=id,conversation_id,recommendation_key,title,status,payload,approved_at,created_at,updated_at&order=updated_at.desc&limit=100`,{serviceRole:true})
  ]);
  const productionOrders=productionOrdersFromRecommendations(inventory.recommendations,inventory.products),live=buildDecisionActions({transfers:presented.transfers,reorders:presented.reorders,discounts:discountResult?.recommendations||[],productionOrders,customerInsight:customerReturns.customer,returnInsight:customerReturns.returns}),persisted=persistedResult.data||[],latest=new Map<string,any>();
  for(const row of persisted)if(!latest.has(row.recommendation_key))latest.set(row.recommendation_key,row);
  const actions=live.map((action:any)=>{const record=latest.get(action.key);return {...action,decision_status:record?.status||'proposed',recommendation_id:record?.id||null,approved_at:record?.approved_at||null,updated_at:record?.updated_at||null}});
  for(const record of persisted){
    if(actions.some((action:any)=>action.key===record.recommendation_key)||!record.payload?.action)continue;
    actions.push({...record.payload.action,decision_status:record.status,recommendation_id:record.id,approved_at:record.approved_at,updated_at:record.updated_at});
  }
  const visible=actions.filter((action:any)=>canAccessPage(context,action.target_page||'action','view')).sort((a:any,b:any)=>{const done=(row:any)=>['approved','executed'].includes(row.decision_status)?1:0,score:any={P0:0,P1:1,P2:2};return done(a)-done(b)||(score[a.priority]??9)-(score[b.priority]??9)||Number(b.impact_amount||0)-Number(a.impact_amount||0)}).slice(0,20);
  return {actions:visible,summary:summarizeDecisionActions(visible),generatedAt:new Date().toISOString(),sources:{inventory:true,forecast:inventory.forecasts.length>0,discount:(discountResult?.recommendations||[]).length>0,production:productionOrders.length>0,customer:Boolean(customerReturns.customer?.hasData),returns:Boolean(customerReturns.returns?.hasData)}};
}

async function responseData(response:Response){const data=await response.json();if(!response.ok){const error:any=new Error(data?.error||'업무 실행에 실패했습니다.');error.status=response.status;throw error}return data}
async function approveDiscountAction(context:any,execution:any){
  requirePagePermission(context,'profitability','approve');const org=context.membership.organization_id,id=String(execution.recommendationId||''),query=new URLSearchParams({id:`eq.${id}`,organization_id:`eq.${org}`,select:'id,decision_status',limit:'1'}),existing=((await supabase(`/rest/v1/discount_recommendation_snapshots?${query}`,{serviceRole:true})).data||[])[0];if(!existing){const error:any=new Error('Discount recommendation not found');error.status=404;throw error}
  const now=new Date().toISOString(),rows=await update('discount_recommendation_snapshots',{id:`eq.${id}`,organization_id:`eq.${org}`},{decision_status:'approved',reviewed_by:context.user.id,reviewed_at:now});await audit(context,'discount_recommendation.reviewed','discount_recommendation',id,{from:existing.decision_status,to:'approved',source:'today_action'});return {recommendation:rows?.[0]};
}
async function persistDecisionAction(context:any,body:any){
  const decision=String(body?.decision||''),allowed=['approved','held','adjustment_requested'];if(!allowed.includes(decision))return json({ok:false,error:'Valid decision is required'},400);
  requirePagePermission(context,'action',decision==='approved'?'approve':'update');const actionKey=String(body?.actionKey||''),snapshot=await decisionActionContext(context),action=snapshot.actions.find((item:any)=>item.key===actionKey);if(!action)return json({ok:false,error:'Decision action not found or no longer current'},404);
  const org=context.membership.organization_id,q=enc(org),key=enc(actionKey),existing=((await supabase(`/rest/v1/ax_recommendations?organization_id=eq.${q}&page_key=eq.action&recommendation_key=eq.${key}&select=id,conversation_id,status,payload&order=updated_at.desc&limit=1`,{serviceRole:true})).data||[])[0];
  if(decision==='approved'&&existing?.status==='approved')return json({ok:true,idempotent:true,action:{...action,decision_status:'approved',recommendation_id:existing.id}});
  let executionResult:any=null;
  if(decision==='approved'){
    const execution=action.execution||{};
    if(execution.action==='approve_transfer')executionResult=await responseData(await approveInventoryTransfer(context,execution));
    else if(execution.action==='approve_reorder')executionResult=await responseData(await approveInventoryReorder(context,execution));
    else if(execution.action==='approve_discount')executionResult=await approveDiscountAction(context,execution);
    else if(execution.action==='update_production_order')executionResult=await responseData(await updateProductionOrder(context,execution));
    else if(execution.action==='create_followup_task')executionResult={queued:true,taskType:execution.taskType,targetPage:execution.targetPage,owner:execution.owner,focus:execution.focus,metrics:execution.metrics,queuedAt:new Date().toISOString()};
    else return json({ok:false,error:'This action has no executable workflow'},400);
  }
  const now=new Date().toISOString();let conversationId=existing?.conversation_id,recommendation:any;
  if(!conversationId)conversationId=(await insert('ax_conversations',{organization_id:org,user_id:context.user.id,title:action.title.slice(0,80),page_key:'action',status:'active'}))?.[0]?.id;
  const values={status:decision,payload:{action,execution_result:executionResult},updated_at:now,approved_by:decision==='approved'?context.user.id:null,approved_at:decision==='approved'?now:null};
  if(existing)recommendation=(await update('ax_recommendations',{id:`eq.${existing.id}`,organization_id:`eq.${org}`},values))?.[0];else recommendation=(await insert('ax_recommendations',{organization_id:org,conversation_id:conversationId,recommendation_key:action.key,page_key:'action',title:action.title,...values,created_by:context.user.id}))?.[0];
  await insert('ax_action_events',{organization_id:org,recommendation_id:recommendation.id,conversation_id:conversationId,actor_user_id:context.user.id,action:decision,payload:{kind:action.kind,execution_result:executionResult}});await audit(context,`today_action.${decision}`,'ax_recommendation',recommendation.id,{actionKey:action.key,kind:action.kind,targetPage:action.target_page,execution:action.execution?.action||null});
  return json({ok:true,action:{...action,decision_status:decision,recommendation_id:recommendation.id,approved_at:recommendation.approved_at},execution:executionResult});
}

export default {async fetch(request:Request){
  if(!['GET','POST','PATCH'].includes(request.method))return json({ok:false,error:'Method not allowed'},405);
  try{
    const context=await requestContext(request),url=new URL(request.url),resource=url.searchParams.get('resource');
    if(request.method==='GET'){
      if(resource==='profitability-summary'){const data=await profitabilitySummary(context);return json({ok:true,source:'supabase_profitability',dataMode:'connected',...data})}
      if(resource==='decision-actions'){const data=await decisionActionContext(context);return json({ok:true,source:'operational_decision_engine',...data})}
      if(resource==='product-intelligence'){const page=String(url.searchParams.get('page')||'market');requirePagePermission(context,page,'view');const data=await productIntelligence(context,page,Number(url.searchParams.get('limit'))||30);return json({ok:true,source:'precomputed_intelligence',...data})}
      if(resource==='discount-intelligence'){const page='profitability';requirePagePermission(context,page,'view');const data=await discountIntelligence(context,page,Number(url.searchParams.get('limit'))||40);return json({ok:true,source:'precomputed_discount_optimizer',...data})}
      if(resource==='customer-insights'){requirePagePermission(context,'customers','view');const data=await customerReturnContext(context);return json({ok:true,source:'supabase_customer_region',generatedAt:new Date().toISOString(),periodDays:data.periodDays,...summarizeCustomerInsights(data.orders)})}
      if(resource==='return-insights'){requirePagePermission(context,'returns','view');const data=await customerReturnContext(context);return json({ok:true,source:'supabase_returns',generatedAt:new Date().toISOString(),periodDays:data.periodDays,...summarizeReturnInsights(data.orders,data.lines,data.products)})}
      if(resource==='inventory-workflows'){requirePagePermission(context,'inventory','view');const data=await inventoryWorkflowContext(context);return json({ok:true,source:'supabase_inventory_operations',generatedAt:new Date().toISOString(),...presentInventoryWorkflow(data)})}
      if(resource==='production-workflows'){const data=await productionWorkflow(context);return json({ok:true,source:'approved_reorder_queue',generatedAt:new Date().toISOString(),...data})}
      if(resource==='inventory-operations'){
        requirePagePermission(context,'inventory','view');const org=context.membership.organization_id,q=encodeURIComponent(org),periodDays=14,end=new Date(),start=new Date(end.getTime()-periodDays*86400000);
        const [snapshots,skus,masterProducts,masterLocations,orders,inventorySources]=await Promise.all([
          latestInventorySnapshots(org,10000),
          supabase(`/rest/v1/skus?organization_id=eq.${q}&select=id,sku_code,product_id,size,color&limit=5000`,{serviceRole:true}),
          supabase(`/rest/v1/products?organization_id=eq.${q}&select=id,product_code,product_name,image_url&limit=5000`,{serviceRole:true}),
          supabase(`/rest/v1/locations?organization_id=eq.${q}&select=id,location_code,location_name,location_type,country_code&limit=5000`,{serviceRole:true}),
          supabase(`/rest/v1/sales_orders?organization_id=eq.${q}&ordered_at=gte.${encodeURIComponent(start.toISOString())}&ordered_at=lt.${encodeURIComponent(end.toISOString())}&select=id,location_id,country_code,channel_code&limit=10000`,{serviceRole:true}),
          supabase(`/rest/v1/data_sources?organization_id=eq.${encodeURIComponent(org)}&provider=eq.file_upload_inventory_snapshot&select=id,name,status,data_mode,last_synced_at,last_successful_sync_at,last_sync_error&order=last_synced_at.desc.nullslast&limit=1`,{serviceRole:true})
        ]);
        const orderIds=new Set((orders.data||[]).map((row:any)=>String(row.id))),allLines=orderIds.size?(await supabase(`/rest/v1/sales_order_lines?organization_id=eq.${q}&select=order_id,sku_id,quantity&limit=20000`,{serviceRole:true})).data||[]:[],lines=allLines.filter((row:any)=>orderIds.has(String(row.order_id)));
        const summary=summarizeInventorySnapshot({snapshots:snapshots.data||[],skus:skus.data||[],products:masterProducts.data||[],locations:masterLocations.data||[],orders:orders.data||[],lines,periodDays,allowedCountries:scopedValues(context,'countries'),allowedChannels:scopedValues(context,'channels'),allowedLocations:scopedValues(context,'locations')});
        const source=inventorySources.data?.[0]||null,stale=source?.data_mode==='stale'||source?.status==='error';
        const diagnostics={readAuthorization:'server',readMode:(snapshots as any).readMode||'organization',latestInventoryJobId:(snapshots as any).importJob?.id||null,snapshotRows:(snapshots.data||[]).length,skuRows:(skus.data||[]).length,productRows:(masterProducts.data||[]).length,locationRows:(masterLocations.data||[]).length,orderRows:(orders.data||[]).length,lineRows:lines.length,scopedProductRows:summary.products.length,scopedLocationRows:summary.locations.length,role:context.membership.role,dataScope:context.membership.data_scope||null};
        return json({ok:true,source:'supabase_inventory',dataMode:stale?'stale':'connected',generatedAt:new Date().toISOString(),lastSnapshotAt:summary.latestSnapshotAt,lastSuccessfulSyncAt:source?.last_successful_sync_at||null,sourceStatus:source,hasData:summary.products.length>0,products:summary.products,locations:summary.locations,diagnostics});
      }
      requirePagePermission(context,'hub','view');
      const [channels,locations,products,daily,inventory]=await Promise.all([
        overviewRows(context,'hub','net_sales','channel',14),overviewRows(context,'hub','net_sales','location',14),overviewRows(context,'hub','net_sales','product',14),overviewRows(context,'hub','net_sales','day',14),overviewRows(context,'inventory','available_qty','product',14)
      ]);
      const sourceQuery=new URLSearchParams({organization_id:`eq.${context.membership.organization_id}`,select:'id,name,provider,status,data_mode,last_synced_at,last_successful_sync_at,last_sync_error',order:'last_synced_at.desc.nullslast'}),sources=(await supabase(`/rest/v1/data_sources?${sourceQuery}`,{serviceRole:true})).data||[],salesSources=sources.filter((item:any)=>String(item.provider||'').includes('sales')||item.source_type!=='file'),stale=salesSources.some((item:any)=>item.data_mode==='stale'||item.status==='error'),lastSuccessful=salesSources.map((item:any)=>item.last_successful_sync_at).filter(Boolean).sort().at(-1)||null;
      return json({ok:true,source:'supabase',dataMode:stale?'stale':'connected',generatedAt:new Date().toISOString(),lastSuccessfulSyncAt:lastSuccessful,sources:salesSources,hasData:channels.length>0,summary:{netSales:sum(channels,'net_sales'),quantity:sum(channels,'quantity'),orders:sum(channels,'orders'),contributionMargin:sum(channels,'contribution_margin')},channels,locations,products,daily,inventory});
    }
    const body=await bodyJson(request),org=context.membership.organization_id;
    if(resource==='decision-actions')return persistDecisionAction(context,body);
    if(resource==='inventory-workflows'){
      const action=String(body?.action||'');if(action==='approve_transfer')return approveInventoryTransfer(context,body);if(action==='approve_reorder')return approveInventoryReorder(context,body);if(action==='update_shipment')return updateInventoryShipment(context,body);if(action==='refresh_forecast'){requireRole(context,['owner','admin']);await assertAnalyticsRefreshAllowed(org);const horizonDays=Math.min(90,Math.max(14,Number(body?.horizonDays)||28)),asOfDate=new Date().toISOString().slice(0,10),forecast=(await supabase('/rest/v1/rpc/refresh_sales_forecasts',{serviceRole:true,method:'POST',body:{p_organization_id:org,p_as_of_date:asOfDate,p_horizon_days:horizonDays}})).data;await audit(context,'inventory.forecast.refreshed','analytics_pipeline',undefined,{asOfDate,horizonDays,forecast});return json({ok:true,asOfDate,horizonDays,forecast})}return json({ok:false,error:'Unsupported inventory action'},400);
    }
    if(resource==='production-workflows'){const action=String(body?.action||'');if(action==='update_production_order')return updateProductionOrder(context,body);return json({ok:false,error:'Unsupported production action'},400)}
    if(request.method==='PATCH'&&resource==='discount-intelligence'){
      const recommendationId=String(body?.recommendationId||''),status=String(body?.status||'');if(!recommendationId||!['approved','held','adjustment_requested','proposed'].includes(status))return json({ok:false,error:'Valid recommendationId and status are required'},400);
      requirePagePermission(context,'profitability',status==='approved'?'approve':'update');const checkQuery=new URLSearchParams({id:`eq.${recommendationId}`,organization_id:`eq.${org}`,select:'id,decision_status',limit:'1'}),existing=((await supabase(`/rest/v1/discount_recommendation_snapshots?${checkQuery}`,{serviceRole:true})).data||[])[0];if(!existing)return json({ok:false,error:'Discount recommendation not found'},404);
      const now=new Date().toISOString(),rows=await update('discount_recommendation_snapshots',{id:`eq.${recommendationId}`,organization_id:`eq.${org}`},{decision_status:status,reviewed_by:context.user.id,reviewed_at:now});await audit(context,'discount_recommendation.reviewed','discount_recommendation',recommendationId,{from:existing.decision_status,to:status});return json({ok:true,recommendation:rows?.[0]});
    }
    if(request.method==='PATCH'&&resource==='product-intelligence'){
      requirePagePermission(context,'market','update');const matchId=String(body?.matchId||''),status=String(body?.status||'');if(!matchId||!['suggested','confirmed','rejected'].includes(status))return json({ok:false,error:'Valid matchId and status are required'},400);
      const checkQuery=new URLSearchParams({id:`eq.${matchId}`,organization_id:`eq.${org}`,select:'id,match_status',limit:'1'}),existing=((await supabase(`/rest/v1/product_market_matches?${checkQuery}`,{serviceRole:true})).data||[])[0];if(!existing)return json({ok:false,error:'Product match not found'},404);
      const reviewed=status==='suggested'?{reviewed_by:null,reviewed_at:null}:{reviewed_by:context.user.id,reviewed_at:new Date().toISOString()},rows=await update('product_market_matches',{id:`eq.${matchId}`,organization_id:`eq.${org}`},{match_status:status,...reviewed,updated_at:new Date().toISOString()});await audit(context,'product_market_match.reviewed','product_market_match',matchId,{from:existing.match_status,to:status});return json({ok:true,match:rows?.[0]});
    }
    if(body?.action==='refresh_product_intelligence'){
      requireRole(context,['owner','admin']);await assertAnalyticsRefreshAllowed(org);const asOfDate=/^\d{4}-\d{2}-\d{2}$/.test(String(body?.asOfDate||''))?String(body.asOfDate):new Date().toISOString().slice(0,10),horizonDays=Math.min(90,Math.max(1,Number(body?.horizonDays)||14));
      const matches=(await supabase('/rest/v1/rpc/refresh_product_market_matches',{serviceRole:true,method:'POST',body:{p_organization_id:org,p_as_of_date:asOfDate,p_limit_per_product:5}})).data,forecasts=(await supabase('/rest/v1/rpc/refresh_sales_forecasts',{serviceRole:true,method:'POST',body:{p_organization_id:org,p_as_of_date:asOfDate,p_horizon_days:horizonDays}})).data;await audit(context,'intelligence.refreshed','analytics_pipeline',undefined,{asOfDate,horizonDays,matches,forecasts});return json({ok:true,asOfDate,horizonDays,matches,forecasts});
    }
    if(body?.action==='refresh_discount_intelligence'){
      requireRole(context,['owner','admin']);await assertAnalyticsRefreshAllowed(org);const asOfDate=/^\d{4}-\d{2}-\d{2}$/.test(String(body?.asOfDate||''))?String(body.asOfDate):new Date().toISOString().slice(0,10),horizonDays=Math.min(90,Math.max(1,Number(body?.horizonDays)||14));const refresh=(await supabase('/rest/v1/rpc/refresh_discount_recommendations',{serviceRole:true,method:'POST',body:{p_organization_id:org,p_as_of_date:asOfDate,p_horizon_days:horizonDays}})).data;await audit(context,'discount_intelligence.refreshed','analytics_pipeline',undefined,{asOfDate,horizonDays,refresh});return json({ok:true,asOfDate,horizonDays,refresh});
    }
    requirePagePermission(context,String(body?.page||'hub'),'view');const result=await runDashboardQuery(context,body||{});return json({ok:true,...result});
  }catch(error:any){return errorResponse(error,error.status||500)}
}};
