import {bodyJson,errorResponse,json} from '../_lib/http.js';
import {audit,insert,requestContext,requireRole,supabase,update} from '../_lib/supabase.js';

const allowedRoles=['owner','admin','manager','member','viewer'];
const allowedPages=['action','hub','targets','profitability','anomalies','sales','customers','returns','decisions','planning','design','production','inventory','marketing','market','designer','connections','permissions'];

function cleanPermissions(items:any[],org:string,membershipId:string){return (Array.isArray(items)?items:[]).filter(item=>allowedPages.includes(item?.page_key)).map(permission=>({organization_id:org,membership_id:membershipId,page_key:permission.page_key,can_view:Boolean(permission.can_view),can_update:Boolean(permission.can_update),can_approve:Boolean(permission.can_approve),data_scope:permission.data_scope||{}}))}

export default {async fetch(request:Request){
  try{const context=await requestContext(request),org=context.membership.organization_id;
    if(request.method==='GET'){requireRole(context,['owner','admin']);const query=new URLSearchParams({organization_id:`eq.${org}`,select:'id,user_id,role,team_code,status,data_scope,page_permissions(page_key,can_view,can_update,can_approve,data_scope)',order:'created_at'});const memberships=(await supabase(`/rest/v1/organization_memberships?${query}`,{serviceRole:true})).data||[];const authData=(await supabase('/auth/v1/admin/users?page=1&per_page=1000',{serviceRole:true})).data;const authUsers=new Map((authData?.users||[]).map((user:any)=>[user.id,user]));const users=memberships.map((membership:any)=>{const authUser:any=authUsers.get(membership.user_id);return {...membership,email:authUser?.email||null,display_name:authUser?.user_metadata?.display_name||authUser?.email||membership.user_id}});return json({ok:true,users,pages:allowedPages})}
    if(request.method==='POST'){requireRole(context,['owner','admin']);const body=await bodyJson(request),email=String(body?.email||'').trim().toLowerCase();if(!email)return json({ok:false,error:'email is required'},400);const role=body.role||'member';if(!allowedRoles.includes(role))return json({ok:false,error:'Invalid role'},400);if(role==='owner'&&context.membership.role!=='owner')return json({ok:false,error:'Only an owner can invite another owner'},403);const invitation=(await supabase('/auth/v1/invite',{serviceRole:true,method:'POST',body:{email,data:{display_name:body.display_name||email},redirect_to:body.redirect_to||process.env.APP_URL||undefined}})).data,userId=invitation.id||invitation.user?.id;if(!userId)return json({ok:false,error:'Supabase invitation returned no user id'},502);const membership=(await insert('organization_memberships',{organization_id:org,user_id:userId,role,team_code:body.team_code||null,status:'invited',data_scope:body.data_scope||{brands:'all',countries:'all',channels:'all',locations:'all'}},{upsert:true,onConflict:'organization_id,user_id'}))?.[0];const permissions=cleanPermissions(body.permissions,org,membership.id);if(permissions.length)await insert('page_permissions',permissions,{upsert:true,onConflict:'membership_id,page_key'});await audit(context,'membership.invited','membership',membership.id,{email,role,team_code:body.team_code||null});return json({ok:true,user:{...membership,email,display_name:body.display_name||email}},201)}
    if(request.method==='PUT'){requireRole(context,['owner','admin']);const body=await bodyJson(request);if(!body?.membershipId)return json({ok:false,error:'membershipId is required'},400);if(body.role&&!allowedRoles.includes(body.role))return json({ok:false,error:'Invalid role'},400);const targetQuery=new URLSearchParams({id:`eq.${body.membershipId}`,organization_id:`eq.${org}`,select:'id,user_id,role'});const target=((await supabase(`/rest/v1/organization_memberships?${targetQuery}`,{serviceRole:true})).data||[])[0];if(!target)return json({ok:false,error:'Membership not found'},404);if((target.role==='owner'||body.role==='owner')&&context.membership.role!=='owner')return json({ok:false,error:'Only an owner can change owner access'},403);if(target.user_id===context.user.id&&body.status==='disabled')return json({ok:false,error:'You cannot disable your own membership'},400);const values:any={};for(const key of ['role','team_code','status','data_scope'])if(body[key]!==undefined)values[key]=body[key];const rows=Object.keys(values).length?await update('organization_memberships',{id:`eq.${body.membershipId}`,organization_id:`eq.${org}`},values):[];const permissions=cleanPermissions(body.permissions,org,body.membershipId);if(permissions.length)await insert('page_permissions',permissions,{upsert:true,onConflict:'membership_id,page_key'});await audit(context,'membership.updated','membership',body.membershipId,{fields:Object.keys(values),permissionCount:permissions.length});return json({ok:true,membership:rows?.[0]||target})}
    return json({ok:false,error:'Method not allowed'},405)
  }catch(error:any){return errorResponse(error,error.status||500)}
}};
