import {bodyJson,errorResponse,json} from '../_lib/http.js';
import {evaluateClosedBetaReadiness} from '../_lib/closed-beta-readiness.js';
import {headerSignature} from '../_lib/mapping-templates.js';
import {inferSalesMapping} from '../_lib/sales.js';
import {audit,downloadStorageObject,insert,requestContext,requireRole,supabase,update} from '../_lib/supabase.js';
import {inferMapping,parseWorkbook} from '../_lib/wms.js';
import {defaultPagePermissions,permissionPageKeys} from '../_lib/default-permissions.js';

const allowedRoles=['owner','admin','manager','member','viewer'];
const allowedPages=permissionPageKeys;
const allowedStatuses=['active','invited','disabled'];

function cleanPermissions(items:any[],org:string,membershipId:string){return (Array.isArray(items)?items:[]).filter(item=>allowedPages.includes(item?.page_key)).map(permission=>({organization_id:org,membership_id:membershipId,page_key:permission.page_key,can_view:Boolean(permission.can_view),can_update:Boolean(permission.can_update),can_approve:Boolean(permission.can_approve),data_scope:permission.data_scope||{}}))}

export default {async fetch(request:Request){
  try{const context=await requestContext(request),org=context.membership.organization_id,url=new URL(request.url);
    if(request.method==='GET'){requireRole(context,['owner','admin']);if(url.searchParams.get('resource')==='audit')return auditHistory(org,url);if(url.searchParams.get('resource')==='readiness')return closedBetaReadiness(org);const query=new URLSearchParams({organization_id:`eq.${org}`,select:'id,user_id,role,team_code,status,data_scope,page_permissions(page_key,can_view,can_update,can_approve,data_scope)',order:'created_at'});const memberships=(await supabase(`/rest/v1/organization_memberships?${query}`,{serviceRole:true})).data||[];const authData=(await supabase('/auth/v1/admin/users?page=1&per_page=1000',{serviceRole:true})).data;const authUsers=new Map((authData?.users||[]).map((user:any)=>[user.id,user]));const users=memberships.map((membership:any)=>{const authUser:any=authUsers.get(membership.user_id);return {...membership,email:authUser?.email||null,display_name:authUser?.user_metadata?.display_name||authUser?.email||membership.user_id}});return json({ok:true,users,pages:allowedPages})}
    if(request.method==='POST'){requireRole(context,['owner','admin']);const body=await bodyJson(request);if(body?.action==='repair_beta_foundation')return repairBetaFoundation(context,org);const email=String(body?.email||'').trim().toLowerCase();if(!email)return json({ok:false,error:'email is required'},400);const role=body.role||'member';if(!allowedRoles.includes(role))return json({ok:false,error:'Invalid role'},400);if(role==='owner'&&context.membership.role!=='owner')return json({ok:false,error:'Only an owner can invite another owner'},403);const invitation=(await supabase('/auth/v1/invite',{serviceRole:true,method:'POST',body:{email,data:{display_name:body.display_name||email},redirect_to:body.redirect_to||process.env.APP_URL||undefined}})).data,userId=invitation.id||invitation.user?.id;if(!userId)return json({ok:false,error:'Supabase invitation returned no user id'},502);const membership=(await insert('organization_memberships',{organization_id:org,user_id:userId,role,team_code:body.team_code||null,status:'invited',data_scope:body.data_scope||{brands:'all',countries:'all',channels:'all',locations:'all'}},{upsert:true,onConflict:'organization_id,user_id'}))?.[0];const requested=cleanPermissions(body.permissions,org,membership.id),permissions=requested.length?requested:defaultPagePermissions(role,body.team_code||'',org,membership.id);if(permissions.length)await insert('page_permissions',permissions,{upsert:true,onConflict:'membership_id,page_key'});await audit(context,'membership.invited','membership',membership.id,{email,role,team_code:body.team_code||null,permissionCount:permissions.length});return json({ok:true,user:{...membership,email,display_name:body.display_name||email,page_permissions:permissions}},201)}
    if(request.method==='PUT'){requireRole(context,['owner','admin']);const body=await bodyJson(request);if(!body?.membershipId)return json({ok:false,error:'membershipId is required'},400);if(body.role&&!allowedRoles.includes(body.role))return json({ok:false,error:'Invalid role'},400);if(body.status&&!allowedStatuses.includes(body.status))return json({ok:false,error:'Invalid status'},400);const targetQuery=new URLSearchParams({id:`eq.${body.membershipId}`,organization_id:`eq.${org}`,select:'id,user_id,role'});const target=((await supabase(`/rest/v1/organization_memberships?${targetQuery}`,{serviceRole:true})).data||[])[0];if(!target)return json({ok:false,error:'Membership not found'},404);if((target.role==='owner'||body.role==='owner')&&context.membership.role!=='owner')return json({ok:false,error:'Only an owner can change owner access'},403);if(target.user_id===context.user.id&&body.status==='disabled')return json({ok:false,error:'You cannot disable your own membership'},400);const values:any={};for(const key of ['role','team_code','status','data_scope'])if(body[key]!==undefined)values[key]=body[key];const rows=Object.keys(values).length?await update('organization_memberships',{id:`eq.${body.membershipId}`,organization_id:`eq.${org}`},values):[];const permissions=cleanPermissions(body.permissions,org,body.membershipId);if(permissions.length)await insert('page_permissions',permissions,{upsert:true,onConflict:'membership_id,page_key'});await audit(context,'membership.updated','membership',body.membershipId,{fields:Object.keys(values),permissionCount:permissions.length});return json({ok:true,membership:rows?.[0]||target})}
    return json({ok:false,error:'Method not allowed'},405)
  }catch(error:any){return errorResponse(error,error.status||500)}
}};

async function auditHistory(org:string,url:URL){
  const limit=Math.min(100,Math.max(1,Number(url.searchParams.get('limit'))||40)),query=new URLSearchParams({organization_id:`eq.${org}`,select:'id,actor_user_id,action,resource_type,resource_id,metadata,created_at',order:'created_at.desc',limit:String(limit)}),events=(await supabase(`/rest/v1/audit_logs?${query}`,{serviceRole:true})).data||[],actorIds=[...new Set(events.map((event:any)=>event.actor_user_id).filter(Boolean))],authData=(await supabase('/auth/v1/admin/users?page=1&per_page=1000',{serviceRole:true})).data,authUsers=new Map((authData?.users||[]).filter((user:any)=>actorIds.includes(user.id)).map((user:any)=>[user.id,user]));
  return json({ok:true,events:events.map((event:any)=>{const actor:any=authUsers.get(event.actor_user_id);return {...event,actor_email:actor?.email||null,actor_name:actor?.user_metadata?.display_name||actor?.email||'시스템'}})});
}

async function closedBetaReadiness(org:string){
  const [members,permissions,orders,lines,snapshots,jobs,mappings,runs,conversations,audits,recommendations,transfers,sources]=await Promise.all([
    rows('organization_memberships',{organization_id:`eq.${org}`,status:'eq.active',select:'id,role'}),rows('page_permissions',{organization_id:`eq.${org}`,select:'id,membership_id,page_key'}),rows('sales_orders',{organization_id:`eq.${org}`,select:'id',limit:'20000'}),rows('sales_order_lines',{organization_id:`eq.${org}`,select:'id',limit:'50000'}),rows('inventory_snapshots',{organization_id:`eq.${org}`,select:'id',limit:'50000'}),rows('import_jobs',{organization_id:`eq.${org}`,entity_type:'in.(sales_order,inventory_snapshot)',select:'id,entity_type,status,summary,completed_at,created_at',order:'created_at.desc',limit:'100'}),rows('mapping_templates',{organization_id:`eq.${org}`,active:'eq.true',entity_type:'in.(sales_order,inventory_snapshot)',select:'id,entity_type',limit:'1000'}),rows('analytics_refresh_runs',{organization_id:`eq.${org}`,select:'id,pipeline,status,error_message,started_at,completed_at',order:'started_at.desc',limit:'100'}),rows('ax_conversations',{organization_id:`eq.${org}`,select:'id',limit:'10000'}),rows('audit_logs',{organization_id:`eq.${org}`,select:'id,action',limit:'20000'}),rows('ax_recommendations',{organization_id:`eq.${org}`,select:'id,recommendation_key,page_key,status,payload',order:'updated_at.desc',limit:'2000'}),rows('transfer_orders',{organization_id:`eq.${org}`,status:'in.(approved,in_transit,completed)',select:'id,status',limit:'2000'}),rows('data_sources',{organization_id:`eq.${org}`,select:'id,status,data_mode,last_sync_error',limit:'1000'})
  ]),latestImport=(type:string)=>jobs.find((job:any)=>job.entity_type===type&&['completed','partial'].includes(job.status)),latestRuns=new Map<string,any>();for(const run of runs)if(!latestRuns.has(String(run.pipeline)))latestRuns.set(String(run.pipeline),run);
  const approvedRecommendations=recommendations.filter((row:any)=>['approved','executed'].includes(row.status)),productionOrders=approvedRecommendations.filter((row:any)=>row.page_key==='inventory'&&String(row.recommendation_key||'').startsWith('reorder:')&&row.payload?.kind==='reorder'&&Number(row.payload?.quantity||0)>0),integrityIssues=approvedRecommendations.filter((row:any)=>row.page_key==='inventory'&&String(row.recommendation_key||'').startsWith('reorder:')&&(row.payload?.kind!=='reorder'||Number(row.payload?.quantity||0)<=0||!row.payload?.product_code||!row.payload?.production_status)),input={activeMembers:members.length,ownerAdmins:members.filter((row:any)=>['owner','admin'].includes(row.role)).length,scopedMembers:members.filter((row:any)=>!['owner','admin'].includes(row.role)).length,permissionRows:permissions.length,salesOrders:orders.length,salesLines:lines.length,inventorySnapshots:snapshots.length,completedSalesImports:jobs.filter((row:any)=>row.entity_type==='sales_order'&&['completed','partial'].includes(row.status)).length,completedInventoryImports:jobs.filter((row:any)=>row.entity_type==='inventory_snapshot'&&['completed','partial'].includes(row.status)).length,salesMappings:mappings.filter((row:any)=>row.entity_type==='sales_order').length,inventoryMappings:mappings.filter((row:any)=>row.entity_type==='inventory_snapshot').length,salesReconciliation:reconciliationStatus(latestImport('sales_order')),inventoryReconciliation:reconciliationStatus(latestImport('inventory_snapshot')),analyticsRuns:latestRuns.size,analyticsFailures:[...latestRuns.values()].filter((row:any)=>row.status==='failed').length,axConversations:conversations.length,auditEvents:audits.length,approvedActions:approvedRecommendations.length+transfers.length,productionOrders:productionOrders.length,reorderIntegrityIssues:integrityIssues.length,sourceErrors:sources.filter((row:any)=>row.status==='error'||row.data_mode==='stale').length,openaiConfigured:Boolean(process.env.OPENAI_API_KEY)};
  return json({ok:true,organizationId:org,...evaluateClosedBetaReadiness(input as any),metrics:input,operations:{latestImports:{sales:latestImport('sales_order')||null,inventory:latestImport('inventory_snapshot')||null},latestAnalytics:[...latestRuns.values()],sourceErrors:sources.filter((row:any)=>row.status==='error'||row.data_mode==='stale')}});
}
async function rows(table:string,params:Record<string,string>){return (await supabase(`/rest/v1/${table}?${new URLSearchParams(params)}`,{serviceRole:true})).data||[]}
function reconciliationStatus(job:any):'matched'|'mismatch'|'missing'{const value=job?.summary?.reconciliation?.status;return value==='matched'?'matched':value==='mismatch'?'mismatch':'missing'}

async function repairBetaFoundation(context:any,org:string){
  const jobs=await rows('import_jobs',{organization_id:`eq.${org}`,status:'in.(completed,partial)',entity_type:'in.(sales_order,inventory_snapshot)',select:'id,raw_upload_id,entity_type,summary,created_at',order:'created_at.desc',limit:'100'}),latest=['sales_order','inventory_snapshot'].map(type=>jobs.find((job:any)=>job.entity_type===type)).filter(Boolean),uploadIds=latest.map((job:any)=>job.raw_upload_id).filter(Boolean),uploads=uploadIds.length?await rows('raw_uploads',{organization_id:`eq.${org}`,id:`in.(${uploadIds.join(',')})`,select:'id,original_filename,storage_path'}):[],uploadMap=new Map(uploads.map((row:any)=>[String(row.id),row])),created:any[]=[];
  for(const job of latest){const upload:any=uploadMap.get(String(job.raw_upload_id));if(!upload?.storage_path)continue;const bytes=await downloadStorageObject('raw-imports',upload.storage_path),file={name:upload.original_filename||'company-data.csv',arrayBuffer:async()=>bytes} as File,sourceRows=await parseWorkbook(file),headers=Object.keys(sourceRows[0]||{}),signature=await headerSignature(headers),existing=await rows('mapping_templates',{organization_id:`eq.${org}`,entity_type:`eq.${job.entity_type}`,header_signature:`eq.${signature}`,active:'eq.true',select:'id',limit:'1'});if(existing.length)continue;const mapping=job.summary?.mapping||(job.entity_type==='sales_order'?inferSalesMapping(headers):inferMapping(headers)),template=(await insert('mapping_templates',{organization_id:org,data_source_id:null,name:`${String(upload.original_filename||job.entity_type).replace(/\.[^.]+$/,'').slice(0,60)} · 기존 적재 복구`,entity_type:job.entity_type,header_signature:signature,mapping,transformations:{source:'legacy_import_repair',import_job_id:job.id},version:1,active:true,created_by:context.user.id}))?.[0];if(template)created.push(template)}
  await audit(context,'mapping_template.legacy_repaired','mapping_template',undefined,{created:created.map(row=>row.id),entityTypes:created.map(row=>row.entity_type)});
  return json({ok:true,created:created.length,templates:created});
}
